___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/wJW61Y2/Used-cars.jpg width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Capstone Project of Data Analytics Module</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Car Price Prediction EDA</p>

## Introduction
Welcome to "***AutoScout Data Analysis Project***". This is the capstone project of ***Data Analysis*** Module. **Auto Scout** data which using for this project, scraped from the on-line car trading company in 2019, contains many features of 9 different car models. In this project, you will have the opportunity to apply many commonly used algorithms for Data Cleaning and Exploratory Data Analysis by using many Python libraries such as Numpy, Pandas, Matplotlib, Seaborn, Scipy you will analyze clean dataset.

### Some Reminders on Exploratory data analysis (EDA)

Exploratory data analysis (EDA) is an especially important activity in the routine of a data analyst or scientist. It enables an in depth understanding of the dataset, define or discard hypotheses and create predictive models on a solid basis. It uses data manipulation techniques and several statistical tools to describe and understand the relationship between variables and how these can impact business. By means of EDA, we can obtain meaningful insights that can impact analysis under the following questions (If a checklist is good enough for pilots to use every flight, it’s good enough for data scientists to use with every dataset).
1. What question are you trying to solve (or prove wrong)?
2. What kind of data do you have?
3. What’s missing from the data?
4. Where are the outliers?
5. How can you add, change or remove features to get more out of your data?

**``Exploratory data analysis (EDA)``** is often an **iterative brainstorming process** where you pose a question, review the data, and develop further questions to investigate before beginning model development work. The image below shows how the brainstorming phase is connected with that of understanding the variables and how this in turn is connected again with the brainstorming phase.<br>

<img src=https://i.ibb.co/k0MC950/EDA-Process.png width="300" height="100">

[Image Credit: Andrew D.](https://towardsdatascience.com/exploratory-data-analysis-in-python-a-step-by-step-process-d0dfa6bf94ee)

**``In this context, the project consists of 3 parts in general:``**
* **The first part** is related to 'Data Cleaning'. It deals with Incorrect Headers, Incorrect Format, Anomalies, and Dropping useless columns.
* **The second part** is related to 'Filling Data', in other words 'Imputation'. It deals with Missing Values. Categorical to numeric transformation is done as well.
* **The third part** is related to 'Handling Outliers of Data' via Visualization libraries. So, some insights will be extracted.

**``NOTE:``**  However, you are free to create your own style. You do NOT have to stick to the steps above. We, the DA & DV instructors, recommend you study each part separately to create a source notebook for each part title for your further studies.

# PART- 1 `( Data Cleaning )`

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import patches
import seaborn as sns

import warnings

# Statistics functions
from scipy.stats import norm
from scipy import stats
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [43]:
# Suppressing a warning 
warnings.filterwarnings("ignore") 

# It is a magic function that renders the figure in the notebook
%matplotlib inline 

# Changing the figure size of a seaborn axes 
sns.set(rc={"figure.figsize": (10, 6)})

# The style parameters control properties like the color of the background and whether a grid is enabled by default.
sns.set_style("whitegrid")

# To display maximum columns
pd.set_option('display.max_columns', None)

# To display maximum columns
#pd.set_option('display.max_rows', 16000)

In [44]:
df = pd.read_json("scout_car.json", lines=True)

In [45]:
df_copy = df.copy()

In [46]:
df.head()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,Type,Previous Owners,Next Inspection,Inspection new,Warranty,Full Service,Non-smoking Vehicle,null,Make,Model,Offer Number,First Registration,Body Color,Paint Type,Body Color Original,Upholstery,Body,Nr. of Doors,Nr. of Seats,Model Code,Gearing Type,Displacement,Cylinders,Weight,Drive chain,Fuel,Consumption,CO2 Emission,Emission Class,\nComfort & Convenience\n,\nEntertainment & Media\n,\nExtras\n,\nSafety & Security\n,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770,VAT deductible,"56,013 km",01/2016,2 previous owners,NaN,66 kW,"[, Used, , Diesel (Particulate Filter)]",\n2\n,"[\n06/2021\n, \n99 g CO2/km (comb)\n]","[\nYes\n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]","[\n, \n]","[\n, \n]",[],\nAudi\n,"[\n, A1, \n]",[\nLR-062483\n],"[\n, 2016, \n]","[\n, Black, \n]",[\nMetallic\n],[\nMythosschwarz\n],"[\nCloth, Black\n]","[\n, Sedans, \n]",[\n5\n],[\n5\n],[\n0588/BDF\n],"[\n, Automatic, \n]","[\n1,422 cc\n]",[\n3\n],"[\n1,220 kg\n]",[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...",[\n99 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Armrest, Automatic climate ...","[Bluetooth, Hands-free equipment, On-board com...","[Alloy wheels, Catalytic Converter, Voice Cont...","[ABS, Central door lock, Daytime running light...","[\n, Sicherheit:, , Deaktivierung für Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.8 TFSI sport,Sedans,14500,Price negotiable,"80,000 km",03/2017,None,NaN,141 kW,"[, Used, , Gasoline]",NaN,NaN,NaN,NaN,NaN,NaN,[],\nAudi\n,"[\n, A1, \n]",NaN,"[\n, 2017, \n]","[\n, Red, \n]",NaN,NaN,"[\nCloth, Grey\n]","[\n, Sedans, \n]",[\n3\n],[\n4\n],[\n0588/BCY\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,255 kg\n]",[\nfront\n],"[\n, Gasoline, \n]","[[5.6 l/100 km (comb)], [7.1 l/100 km (city)],...",[\n129 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...","[Bluetooth, Hands-free equipment, On-board com...","[Alloy wheels, Sport seats, Sport suspension, ...","[ABS, Central door lock, Central door lock wit...",[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640,VAT deductible,"83,450 km",02/2016,1 previous owner,NaN,85 kW,"[, Used, , Diesel (Particulate Filter)]",\n1\n,NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]",NaN,NaN,[],\nAudi\n,"[\n, A1, \n]",[\nAM-95365\n],"[\n, 2016, \n]","[\n, Black, \n]",[\nMetallic\n],[\nmythosschwarz metallic\n],"[\nCloth, Black\n]","[\n, Sedans, \n]",[\n4\n],[\n4\n],NaN,"[\n, Automatic, \n]","[\n1,598 cc\n]",NaN,NaN,[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[3.8 l/100 km (comb)], [4.4 l/100 km (city)],...",[\n99 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Cruise control, Electrical ...","[MP3, On-board computer]","[Alloy wheels, Voice Control]","[ABS, Central door lock, Daytime running light...","[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.4 TDi Design S tronic,Sedans,14500,None,"73,000 km",08/2016,1 previous owner,NaN,66 kW,"[, Used, , Diesel (Particulate Filter)]",\n1\n,NaN,NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]",[],\nAudi\n,"[\n, A1, \n]",NaN,"[\n, 2016, \n]","[\n, Brown, \n]",[\nMetallic\n],NaN,NaN,"[\n, Sedans, \n]",[\n3\n],[\n4\n],NaN,"[\n, Automatic, \n]","[\n1,422 cc\n]",[\n3\n],"[\n1,195 kg\n]",NaN,"[\n, Diesel (Particulate Filter), \n]","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...",[\n99 g CO2/km (comb)\n],[\nEuro 6\n],"[Air suspension, Armrest, Auxiliary heating, E...","[Bluetooth, CD player, Hands-free equipment, M...","[Alloy wheels, Sport seats, Voice Control]","[ABS, Alarm system, Central door lock with rem...","[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790,None,"16,200 km",05/2016,1 previous owner,NaN,66 kW,"[, Used, , Diesel (Particulate Filter)]",\n1\n,NaN,"[\nYes\n, \n109 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]","[\n, \n]",[],\nAudi\n,"[\n, A1, \n]",[\nC1626\n],"[\n, 2016, \n]","[\n, Black, \n]",[\nMetallic\n],[\nMythosschwarz Metallic\n],"[\nCloth, Black\n]","[\n, Sedans, \n]",[\n5\n],[\n5\n],[\n0588/BDF\n],"[\n, Automatic, \n]","[\n1,422 cc\n]",[\n3\n],NaN,[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[4.1 l/100 km (comb)], [4.6 l/100 km (city)],...",[\n109 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Armrest, Automatic climate ...","[Bluetooth, CD player, Hands-free equipment, M...","[Alloy wheels, Sport package, Sport suspension...","[ABS, Central door lock, Driver-side airbag, E...","[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.sample(5).T

,7872,10790,14532,8371,14553
url,https://www.autoscout24.com//offers/opel-astra...,https://www.autoscout24.com//offers/opel-insig...,https://www.autoscout24.com//offers/renault-cl...,https://www.autoscout24.com//offers/opel-corsa...,https://www.autoscout24.com//offers/renault-cl...
make_model,Opel Astra,Opel Insignia,Renault Clio,Opel Corsa,Renault Clio
short_description,"V Elite 1,4 110KW / 150PS",ST 1.6CDTI ecoFlex CDTi Selective Automático,1.5 dCi 75ch energy Life Euro6C 5p,"E Color Edition Automatik, Top Fahrzeug",TCe Energy Limited 66kW
body_type,Sedans,Sedans,Sedans,Compact,Sedans
price,22590,10990,10790,12990,10500
vat,VAT deductible,VAT deductible,None,VAT deductible,None
km,20 km,"95,000 km",10 km,"30,000 km","18,700 km"
registration,-/-,07/2016,06/2018,04/2016,03/2018
prev_owner,None,1 previous owner,None,1 previous owner,1 previous owner
kW,NaN,NaN,NaN,NaN,NaN
hp,110 kW,100 kW,56 kW,66 kW,66 kW
Type,"[, New, , Super 95]","[, Used, , Diesel]","[, Used, , Diesel]","[, Used, , Super 95 / Regular/Benzine 91]","[, Used, , Gasoline]"
Previous Owners,NaN,\n1\n,NaN,\n1\n,\n1\n
Next Inspection,NaN,NaN,NaN,NaN,NaN
Inspection new,\nYes\n,NaN,NaN,"[\nYes\n, \n, 5.9 l/100 km (comb), \n, 7.9 l/1...",NaN
Warranty,NaN,"[\n12 months\n, \n99 g CO2/km (comb)\n]",\n12 months\n,"[\n60 months\n, \n137 g CO2/km (comb)\n]","[\n24 months\n, \n105 g CO2/km (comb)\n]"
Full Service,"[\n, \n, \n139 g CO2/km (comb)\n]",NaN,NaN,"[\n, \n, \nEuro 6\n]","[\n, \n, \nEuro 6\n]"
Non-smoking Vehicle,"[\n, \n, \nEuro 6d-TEMP\n]",NaN,NaN,"[\n, \n, \n4 (Green)\n]","[\n, \n]"
null,[],[],[],[],[]
Make,\nOpel\n,\nOpel\n,\nRenault\n,\nOpel\n,\nRenault\n
Model,"[\n, Astra, \n]","[\n, Insignia, \n]","[\n, Clio, \n]","[\n, Corsa, \n]","[\n, Clio, \n]"
Offer Number,[\nT44458\n],[\n163500\n],[\nre13c1-EY-178-DC\n],[\n68G4210003\n],[\n5041KJB\n]
First Registration,NaN,"[\n, 2016, \n]","[\n, 2018, \n]","[\n, 2016, \n]","[\n, 2018, \n]"
Body Color,"[\n, Grey, \n]","[\n, Grey, \n]","[\n, White, \n]","[\n, White, \n]","[\n, Grey, \n]"
Paint Type,[\nMetallic\n],[\nMetallic\n],NaN,NaN,[\nMetallic\n]
Body Color Original,[\nGrau Metallic\n],NaN,[\nBLANC\n],[\nSchneeWeiss/SummitWhite/Arctic\n],NaN
Upholstery,"[\nCloth, Grey\n]","[\nCloth, Grey\n]",NaN,"[\nCloth, Black\n]",NaN
Body,"[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Compact, \n]","[\n, Sedans, \n]"
Nr. of Doors,[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n]
Nr. of Seats,NaN,[\n5\n],[\n5\n],[\n5\n],[\n5\n]
Model Code,NaN,NaN,NaN,NaN,NaN
Gearing Type,"[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Manual, \n]","[\n, Automatic, \n]","[\n, Manual, \n]"
Displacement,"[\n1,399 cc\n]","[\n1,598 cc\n]","[\n1,461 cc\n]","[\n1,398 cc\n]",[\n898 cc\n]
Cylinders,NaN,[\n4\n],NaN,NaN,[\n3\n]
Weight,"[\n1,273 kg\n]","[\n1,513 kg\n]",NaN,NaN,"[\n1,082 kg\n]"
Drive chain,NaN,[\nfront\n],NaN,NaN,NaN
Fuel,"[\n, Super 95, \n]","[\n, Diesel, \n]","[\n, Diesel, \n]","[\n, Super 95 / Regular/Benzine 91, \n]","[\n, Gasoline, \n]"
Consumption,"[[6.1 l/100 km (comb)], [7.5 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.5 l/100 km (city)],...",NaN,"[\n, 5.9 l/100 km (comb), \n, 7.9 l/100 km (ci...","[[4.7 l/100 km (comb)], [5.7 l/100 km (city)],..."
CO2 Emission,[\n139 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],NaN,[\n137 g CO2/km (comb)\n],[\n105 g CO2/km (comb)\n]
Emission Class,[\nEuro 6d-TEMP\n],[\nEuro 6\n],NaN,NaN,[\nEuro 6\n]
\nComfort & Convenience\n,"[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Cruise control, Electrical side mirrors, Powe...","[Air conditioning, Cruise control, Electricall...","[Air conditioning, Electrical side mirrors, Le..."
\nEntertainment & Media\n,"[Bluetooth, Hands-free equipment, On-board com...",NaN,"[On-board computer, Radio]","[Bluetooth, Hands-free equipment, MP3, On-boar...",NaN
\nExtras\n,[Touch screen],[Alloy wheels],[Alloy wheels],"[Alloy wheels, Sport seats, Sport suspension]",NaN
\nSafety & Security\n,"[ABS, Central door lock, Driver-side airbag, E...","[ABS, Passenger-side airbag, Power steering, S...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light..."
description,"[\n, Innenraum und Komfort, :, Abgedunkelte He...",[\nAUTOS MOLIERE donde la confianza y transpar...,[\nMarque: RENAULTModèle: CLIOVersion: 1.5 dCi...,"[\nIhre Ansprechpartner für dieses KFZ:, , ,...",[\nPrecio sujeto a financiación con RCI Banque...
Emission Label,[\n4 (Green)\n],NaN,NaN,NaN,NaN
Gears,[\n6\n],[\n6\n],NaN,[\n6\n],[\n5\n]
Country version,[\nEuropean Union\n],[\nSpain\n],NaN,[\nGermany\n],[\nSpain\n]
Electricity consumption,NaN,NaN,NaN,NaN,NaN
Last Service Date,NaN,NaN,NaN,NaN,NaN
Other Fuel Types,NaN,NaN,NaN,"[[], [], []]",NaN
Availability,NaN,NaN,NaN,NaN,NaN
Last Timing Belt Service Date,NaN,NaN,NaN,NaN,NaN
Available from,NaN,NaN,NaN,NaN,NaN

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   make_model                     15919 non-null  object
 2   short_description              15873 non-null  object
 3   body_type                      15859 non-null  object
 4   price                          15919 non-null  int64
 5   vat                            11406 non-null  object
 6   km                             15919 non-null  object
 7   registration                   15919 non-null  object
 8   prev_owner                     9091 non-null   object
 9   kW                             0 non-null      float64
 10  hp                             15919 non-null  object
 11  Type                           15917 non-null  object
 12  Previous Owners                9279 non-null   object
 13  Next Inspection                3535 non-null   object
 14  Inspection new                 3932 non-null   object
 15  Warranty                       10499 non-null  object
 16  Full Service                   8215 non-null   object
 17  Non-smoking Vehicle            7177 non-null   object
 18  null                           15919 non-null  object
 19  Make                           15919 non-null  object
 20  Model                          15919 non-null  object
 21  Offer Number                   12744 non-null  object
 22  First Registration             14322 non-null  object
 23  Body Color                     15322 non-null  object
 24  Paint Type                     10147 non-null  object
 25  Body Color Original            12160 non-null  object
 26  Upholstery                     12199 non-null  object
 27  Body                           15859 non-null  object
 28  Nr. of Doors                   15707 non-null  object
 29  Nr. of Seats                   14942 non-null  object
 30  Model Code                     4978 non-null   object
 31  Gearing Type                   15919 non-null  object
 32  Displacement                   15423 non-null  object
 33  Cylinders                      10239 non-null  object
 34  Weight                         8945 non-null   object
 35  Drive chain                    9061 non-null   object
 36  Fuel                           15919 non-null  object
 37  Consumption                    14013 non-null  object
 38  CO2 Emission                   14111 non-null  object
 39  Emission Class                 12898 non-null  object
 40
Comfort & Convenience
        14999 non-null  object
 41
Entertainment & Media
        14545 non-null  object
 42
Extras
                       12957 non-null  object
 43
Safety & Security
            14937 non-null  object
 44  description                    15919 non-null  object
 45  Emission Label                 3985 non-null   object
 46  Gears                          11207 non-null  object
 47  Country version                7586 non-null   object
 48  Electricity consumption        137 non-null    object
 49  Last Service Date              566 non-null    object
 50  Other Fuel Types               880 non-null    object
 51  Availability                   635 non-null    object
 52  Last Timing Belt Service Date  16 non-null     object
 53  Available from                 272 non-null    object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB

In [49]:
# Changing column names
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kW', 'hp', 'Type',
       'Previous Owners', 'Next Inspection', 'Inspection new', 'Warranty',
       'Full Service', 'Non-smoking Vehicle', 'null', 'Make', 'Model',
       'Offer Number', 'First Registration', 'Body Color', 'Paint Type',
       'Body Color Original', 'Upholstery', 'Body', 'Nr. of Doors',
       'Nr. of Seats', 'Model Code', 'Gearing Type', 'Displacement',
       'Cylinders', 'Weight', 'Drive chain', 'Fuel', 'Consumption',
       'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n',
       '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n',
       'description', 'Emission Label', 'Gears', 'Country version',
       'Electricity consumption', 'Last Service Date', 'Other Fuel Types',
       'Availability', 'Last Timing Belt Service Date', 'Available from'],
      dtype='object')

In [50]:
# !pip install skimpy
from skimpy import clean_columns

# columns = df.columns

# messy_df = pd.DataFrame(data = [], columns = columns, index = [0])
# print(messy_df)
# clean_df = clean_columns(messy_df)
# clean_df.columns.tolist()

In [51]:
df = clean_columns(df)  # cleaning column names using skimpy clean_columns method

42 column names have been cleaned

In [52]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'k_w', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'non_smoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co_2_emission', 'emission_class', 'comfort_&_convenience',
       'entertainment_&_media', 'extras', 'safety_&_security', 'description',
       'emission_label', 'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [53]:
df.rename(columns = {'k_w':'kW',
                     'co_2_emission':'co2_emission',
                     'comfort_&_convenience': 'comfort&convenience',
                    'entertainment_&_media':'entertainment&media',
                    'safety_&_security':'safety_&_security'}, inplace = True)

In [54]:
df.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kW', 'hp', 'type',
       'previous_owners', 'next_inspection', 'inspection_new', 'warranty',
       'full_service', 'non_smoking_vehicle', 'null', 'make', 'model',
       'offer_number', 'first_registration', 'body_color', 'paint_type',
       'body_color_original', 'upholstery', 'body', 'nr_of_doors',
       'nr_of_seats', 'model_code', 'gearing_type', 'displacement',
       'cylinders', 'weight', 'drive_chain', 'fuel', 'consumption',
       'co2_emission', 'emission_class', 'comfort&convenience',
       'entertainment&media', 'extras', 'safety_&_security', 'description',
       'emission_label', 'gears', 'country_version', 'electricity_consumption',
       'last_service_date', 'other_fuel_types', 'availability',
       'last_timing_belt_service_date', 'available_from'],
      dtype='object')

In [55]:
df.isnull().sum()

url                                  0
make_model                           0
short_description                   46
body_type                           60
price                                0
vat                               4513
km                                   0
registration                         0
prev_owner                        6828
kW                               15919
hp                                   0
type                                 2
previous_owners                   6640
next_inspection                  12384
inspection_new                   11987
warranty                          5420
full_service                      7704
non_smoking_vehicle               8742
null                                 0
make                                 0
model                                0
offer_number                      3175
first_registration                1597
body_color                         597
paint_type                        5772
body_color_original               3759
upholstery                        3720
body                                60
nr_of_doors                        212
nr_of_seats                        977
model_code                       10941
gearing_type                         0
displacement                       496
cylinders                         5680
weight                            6974
drive_chain                       6858
fuel                                 0
consumption                       1906
co2_emission                      1808
emission_class                    3021
comfort&convenience                920
entertainment&media               1374
extras                            2962
safety_&_security                  982
description                          0
emission_label                   11934
gears                             4712
country_version                   8333
electricity_consumption          15782
last_service_date                15353
other_fuel_types                 15039
availability                     15284
last_timing_belt_service_date    15903
available_from                   15647
dtype: int64

In [56]:
df.isnull().sum()/len(df)*100 # percentages of null values in each column

url                                0.000000
make_model                         0.000000
short_description                  0.288963
body_type                          0.376908
price                              0.000000
vat                               28.349771
km                                 0.000000
registration                       0.000000
prev_owner                        42.892141
kW                               100.000000
hp                                 0.000000
type                               0.012564
previous_owners                   41.711163
next_inspection                   77.793831
inspection_new                    75.299956
warranty                          34.047365
full_service                      48.395000
non_smoking_vehicle               54.915510
null                               0.000000
make                               0.000000
model                              0.000000
offer_number                      19.944720
first_registration                10.032037
body_color                         3.750236
paint_type                        36.258559
body_color_original               23.613292
upholstery                        23.368302
body                               0.376908
nr_of_doors                        1.331742
nr_of_seats                        6.137320
model_code                        68.729192
gearing_type                       0.000000
displacement                       3.115774
cylinders                         35.680633
weight                            43.809285
drive_chain                       43.080596
fuel                               0.000000
consumption                       11.973114
co2_emission                      11.357497
emission_class                    18.977323
comfort&convenience                5.779257
entertainment&media                8.631195
extras                            18.606696
safety_&_security                  6.168729
description                        0.000000
emission_label                    74.967021
gears                             29.599849
country_version                   52.346253
electricity_consumption           99.139393
last_service_date                 96.444500
other_fuel_types                  94.472015
availability                      96.011056
last_timing_belt_service_date     99.899491
available_from                    98.291350
dtype: float64

In [57]:
(df.isna().sum()/df.shape[0]*100).sort_values(ascending=False)

kW                               100.000000
last_timing_belt_service_date     99.899491
electricity_consumption           99.139393
available_from                    98.291350
last_service_date                 96.444500
availability                      96.011056
other_fuel_types                  94.472015
next_inspection                   77.793831
inspection_new                    75.299956
emission_label                    74.967021
model_code                        68.729192
non_smoking_vehicle               54.915510
country_version                   52.346253
full_service                      48.395000
weight                            43.809285
drive_chain                       43.080596
prev_owner                        42.892141
previous_owners                   41.711163
paint_type                        36.258559
cylinders                         35.680633
warranty                          34.047365
gears                             29.599849
vat                               28.349771
body_color_original               23.613292
upholstery                        23.368302
offer_number                      19.944720
emission_class                    18.977323
extras                            18.606696
consumption                       11.973114
co2_emission                      11.357497
first_registration                10.032037
entertainment&media                8.631195
safety_&_security                  6.168729
nr_of_seats                        6.137320
comfort&convenience                5.779257
body_color                         3.750236
displacement                       3.115774
nr_of_doors                        1.331742
body                               0.376908
body_type                          0.376908
short_description                  0.288963
type                               0.012564
fuel                               0.000000
gearing_type                       0.000000
make_model                         0.000000
model                              0.000000
make                               0.000000
description                        0.000000
null                               0.000000
hp                                 0.000000
registration                       0.000000
km                                 0.000000
price                              0.000000
url                                0.000000
dtype: float64

In [58]:
def check_df(col):
    print('column name : ', col)
    print('--------------------------------')
    print('Per_of_Nulls   : ', '%', round(df[col].isnull().sum() / df.shape[0]*100, 2))
    print('Num_of_Nulls   : ', df[col].isnull().sum())
    print(df[col].value_counts(dropna = False))
    print("*"*30)
    print("\n\n")

In [59]:
for col in df.columns :
    check_df(col)

column name :  url
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e                  1
https://www.autoscout24.com//offers/opel-insignia-bus-inno-2-0-cdti-aut-navi-bi-xe-led-e6-diesel-black-8710b253-dd98-4ed0-9d46-cbad2d79532b                1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-10b7463b-9f56-4348-af35-df3432b2b585    1
https://www.autoscout24.com//offers/opel-insignia-2-0cdti-st-business-innovation-navi-bt-diesel-black-ba5a3368-dedc-4e51-9127-3976b26e93c2                 1
https://www.autoscout24.com//offers/opel-insignia-sport-tourer-opel-sport-tourer-1-6-cdti-136-ch-a-c-diesel-silver-7b52f054-78d3-4d5e-9370-8a7d081d7edd    1
                                                                                                                                                          ..
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-black-cf50f7b1-4d7b-466f-93a2-4e11ec0b4107                        1
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-grey-3f47eb34-15c4-4763-860d-78fcbbd2c9ff                         1
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-silver-f7a4bc95-b2ef-4bac-9497-6bcbcd05db0b                       1
https://www.autoscout24.com//offers/audi-a3-sb-30-1-6-tdi-business-116cv-s-tronic-diesel-silver-1c94c7a2-67b5-49ca-ae42-42a6800fb3f5                       1
https://www.autoscout24.com//offers/renault-espace-initiale-paris-tce-225-edc-gpf-navi-shz-aux-gasoline-grey-0bd690d9-7e93-4cab-bc5a-9d5b63402481          1
Name: url, Length: 15919, dtype: int64
******************************



column name :  make_model
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64
******************************



column name :  short_description
--------------------------------
Per_of_Nulls   :  % 0.29
Num_of_Nulls   :  46
SPB 1.6 TDI 116 CV S tronic Sport                 64
None                                              46
1.4 66kW (90CV) Selective                         40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH             38
SPB 30 TDI S tronic Business                      35
                                                  ..
K Sports Tourer Business **Navi*Voll**             1
1.0 Turbo ecoFLEX Automatic Elective Park Navi     1
1.6 CDTI Business *Navi*Automatik*Spurh.*          1
1.6 136 CV Automatica Navi E 6 Garanzia Full       1
TCe 225 EDC GPF LIM Deluxe Pano,RFK                1
Name: short_description, Length: 10002, dtype: int64
******************************



column name :  body_type
--------------------------------
Per_of_Nulls   :  % 0.38
Num_of_Nulls   :  60
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
None               60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64
******************************



column name :  price
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
14990    154
15990    151
10990    139
15900    106
17990    102
        ...
17559      1
17560      1
17570      1
17575      1
39875      1
Name: price, Length: 2956, dtype: int64
******************************



column name :  vat
--------------------------------
Per_of_Nulls   :  % 28.35
Num_of_Nulls   :  4513
VAT deductible      10980
None                 4513
Price negotiable      426
Name: vat, dtype: int64
******************************



column name :  km
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ...
67,469 km       1
43,197 km       1
10,027 km       1
35,882 km       1
57 km           1
Name: km, Length: 6690, dtype: int64
******************************



column name :  registration
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64
******************************



column name :  prev_owner
--------------------------------
Per_of_Nulls   :  % 42.89
Num_of_Nulls   :  6828
1 previous owner     8294
None                 6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64
******************************



column name :  kW
--------------------------------
Per_of_Nulls   :  % 100.0
Num_of_Nulls   :  15919
NaN    15919
Name: kW, dtype: int64
******************************



column name :  hp
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ...
84 kW        1
195 kW       1
44 kW        1
239 kW       1
9 kW         1
Name: hp, Length: 81, dtype: int64
******************************



column name :  type
--------------------------------
Per_of_Nulls   :  % 0.01
Num_of_Nulls   :  2
[, Used, , Diesel (Particulate Filter)]                                                                                 3475
[, Used, , Diesel]                                                                                                      2516
[, Used, , Gasoline]                                                                                                    2367
[, Used, , Super 95]                                                                                                    1818
[, Pre-registered, , Super 95]                                                                                           500
                                                                                                                        ...
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]       1
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                               1
[, Demonstration, , Super Plus 98]                                                                                         1
[, New, , Super Plus E10 98]                                                                                               1
[, Demonstration, , Regular/Benzine E10 91]                                                                                1
Name: type, Length: 170, dtype: int64
******************************



column name :  previous_owners
--------------------------------
Per_of_Nulls   :  % 41.71
Num_of_Nulls   :  6640
\n1\n                                                                                        8101
NaN                                                                                          6640
\n2\n                                                                                         766
\n0\n                                                                                         163
\n3\n                                                                                          17
                                                                                             ...
[\n1\n, \n111 g CO2/km (comb)\n]                                                                1
[\n1\n, \nEuro 6\n]                                                                             1
[\n2\n, \n119 g CO2/km (comb)\n]                                                                1
[\n1\n, \n, 6.6 l/100 km (comb), \n, 8.1 l/100 km (city), \n, 5.7 l/100 km (country), \n]       1
[\n2\n, \n137 g CO2/km (comb)\n]                                                                1
Name: previous_owners, Length: 103, dtype: int64
******************************



column name :  next_inspection
--------------------------------
Per_of_Nulls   :  % 77.79
Num_of_Nulls   :  12384
NaN                                       12384
\n04/2022\n                                  62
\n03/2021\n                                  38
\n03/2022\n                                  36
\n06/2021\n                                  34
                                          ...
[\n12/2018\n, \n97 g CO2/km (comb)\n]         1
[\n03/2022\n, \n1 (No sticker)\n]             1
[\n05/2021\n, \n93 g CO2/km (comb)\n]         1
[\n06/2021\n, \n93 g CO2/km (comb)\n]         1
[\n01/2022\n, \n168 g CO2/km (comb)\n]        1
Name: next_inspection, Length: 1400, dtype: int64
******************************



column name :  inspection_new
--------------------------------
Per_of_Nulls   :  % 75.3
Num_of_Nulls   :  11987
NaN                                                                                            11987
[\nYes\n, \nEuro 6\n]                                                                            523
\nYes\n                                                                                          362
[\nYes\n, \n102 g CO2/km (comb)\n]                                                               174
[\nYes\n, \n4 (Green)\n]                                                                         166
                                                                                               ...
[\nYes\n, \n, 6 l/100 km (comb), \n, 8 l/100 km (city), \n, 4.9 l/100 km (country), \n]            1
[\nYes\n, \n, 6.8 l/100 km (comb), \n, 8.5 l/100 km (city), \n, 6.1 l/100 km (country), \n]        1
[\nYes\n, \n, 4.1 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 5.2 l/100 km (country), \n]        1
[\nYes\n, \n, 5.2 l/100 km (comb), \n, 6.8 l/100 km (city), \n, 4.3 l/100 km (country), \n]        1
[\nYes\n, \n172 g CO2/km (comb)\n]                                                                 1
Name: inspection_new, Length: 203, dtype: int64
******************************



column name :  warranty
--------------------------------
Per_of_Nulls   :  % 34.05
Num_of_Nulls   :  5420
NaN                                                                                                5420
[\n, \n, \nEuro 6\n]                                                                               1868
\n12 months\n                                                                                      1177
\n                                                                                                  979
\n24 months\n                                                                                       566
                                                                                                   ...
[\n72 months\n, \n125 g CO2/km (comb)\n]                                                              1
[\n60 months\n, \n14 g CO2/km (comb)\n]                                                               1
[\n24 months\n, \n121 g CO2/km (comb)\n]                                                              1
[\n12 months\n, \nEuro 6d\n]                                                                          1
[\n36 months\n, \n, 7.4 l/100 km (comb), \n, 9.6 l/100 km (city), \n, 6 l/100 km (country), \n]       1
Name: warranty, Length: 516, dtype: int64
******************************



column name :  full_service
--------------------------------
Per_of_Nulls   :  % 48.39
Num_of_Nulls   :  7704
NaN                                                                                           7704
[\n, \n, \n4 (Green)\n]                                                                       2235
[\n, \n, \nEuro 6\n]                                                                          2097
[\n, \n]                                                                                      1702
[\n, \n, \nEuro 6d-TEMP\n]                                                                     399
                                                                                              ...
[\n, \n, \n80 g CO2/km (comb)\n]                                                                 1
[\n, \n, \n84 g CO2/km (comb)\n]                                                                 1
[\n, \n, \n, 6 l/100 km (comb), \n, 8 l/100 km (city), \n, 4.9 l/100 km (country), \n]           1
[\n, \n, \n, 4.9 l/100 km (comb), \n, 6.2 l/100 km (city), \n, 4.1 l/100 km (country), \n]       1
[\n, \n, \nEuro 4\n]                                                                             1
Name: full_service, Length: 123, dtype: int64
******************************



column name :  non_smoking_vehicle
--------------------------------
Per_of_Nulls   :  % 54.92
Num_of_Nulls   :  8742
NaN                                                                                           8742
[\n, \n]                                                                                      3647
[\n, \n, \n4 (Green)\n]                                                                       1240
[\n, \n, \nEuro 6\n]                                                                          1127
[\n, \n, \nEuro 6d-TEMP\n]                                                                     345
                                                                                              ...
[\n, \n, \n, 5.6 l/100 km (comb), \n, 7.3 l/100 km (city), \n, 4.7 l/100 km (country), \n]       1
[\n, \n, \n122 g CO2/km (comb)\n]                                                                1
[\n, \n, \n158 g CO2/km (comb)\n]                                                                1
[\n, \n, \n150 g CO2/km (comb)\n]                                                                1
[\n, \n, \n175 g CO2/km (comb)\n]                                                                1
Name: non_smoking_vehicle, Length: 95, dtype: int64
******************************



column name :  null
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[]    15919
Name: null, dtype: int64
******************************



column name :  make
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
\nOpel\n       7343
\nAudi\n       5712
\nRenault\n    2864
Name: make, dtype: int64
******************************



column name :  model
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[\n, A3, \n]          3097
[\n, A1, \n]          2614
[\n, Insignia, \n]    2598
[\n, Astra, \n]       2526
[\n, Corsa, \n]       2219
[\n, Clio, \n]        1839
[\n, Espace, \n]       991
[\n, Duster, \n]        34
[\n, A2, \n]             1
Name: model, dtype: int64
******************************



column name :  offer_number
--------------------------------
Per_of_Nulls   :  % 19.94
Num_of_Nulls   :  3175
NaN                                               3175
[\nLT67679\n]                                       27
[\nUN89904\n]                                       27
[\nXJ38068\n]                                       27
[\nJV03654\n]                                       27
                                                  ...
[\n160_dcbb6c3e-a6da-43a3-8754-ccd994cec93b\n]       1
[\n6701576\n]                                        1
[\n6701569\n]                                        1
[\n158121\n]                                         1
[\nRe_30000008029\n]                                 1
Name: offer_number, Length: 11441, dtype: int64
******************************



column name :  first_registration
--------------------------------
Per_of_Nulls   :  % 10.03
Num_of_Nulls   :  1597
[\n, 2018, \n]    4522
[\n, 2016, \n]    3674
[\n, 2017, \n]    3273
[\n, 2019, \n]    2853
NaN               1597
Name: first_registration, dtype: int64
******************************



column name :  body_color
--------------------------------
Per_of_Nulls   :  % 3.75
Num_of_Nulls   :  597
[\n, Black, \n]     3745
[\n, Grey, \n]      3505
[\n, White, \n]     3406
[\n, Silver, \n]    1647
[\n, Blue, \n]      1431
[\n, Red, \n]        957
NaN                  597
[\n, Brown, \n]      289
[\n, Green, \n]      154
[\n, Beige, \n]      108
[\n, Yellow, \n]      51
[\n, Violet, \n]      18
[\n, Bronze, \n]       6
[\n, Orange, \n]       3
[\n, Gold, \n]         2
Name: body_color, dtype: int64
******************************



column name :  paint_type
--------------------------------
Per_of_Nulls   :  % 36.26
Num_of_Nulls   :  5772
[\nMetallic\n]       9794
NaN                  5772
[\nUni/basic\n]       347
[\nPerl effect\n]       6
Name: paint_type, dtype: int64
******************************



column name :  body_color_original
--------------------------------
Per_of_Nulls   :  % 23.61
Num_of_Nulls   :  3759
NaN                                    3759
[\nOnyx Schwarz\n]                      338
[\nBianco\n]                            282
[\nMythosschwarz Metallic\n]            238
[\nBrillantschwarz\n]                   216
                                       ...
[\nRouge-Braun (G0Y)\n]                   1
[\nVARI COLRI DISPONIBILI\n]              1
[\nKokosnussbraun Metallic\n]             1
[\nFarbe frei wählbar\n]                  1
[\nPerlmutt-Weiß Metallic (Weiß)\n]       1
Name: body_color_original, Length: 1928, dtype: int64
******************************



column name :  upholstery
--------------------------------
Per_of_Nulls   :  % 23.37
Num_of_Nulls   :  3720
[\nCloth, Black\n]           5821
NaN                          3720
[\nPart leather, Black\n]    1121
[\nCloth\n]                  1005
[\nCloth, Grey\n]             891
[\nCloth, Other\n]            639
[\nFull leather, Black\n]     575
[\nBlack\n]                   491
[\nGrey\n]                    273
[\nOther, Other\n]            182
[\nPart leather\n]            140
[\nFull leather\n]            139
[\nFull leather, Brown\n]     116
[\nPart leather, Grey\n]      116
[\nOther, Black\n]            110
[\nFull leather, Other\n]      72
[\nFull leather, Grey\n]       67
[\nPart leather, Other\n]      65
[\nOther\n]                    56
[\nPart leather, Brown\n]      50
[\nalcantara, Black\n]         47
[\nVelour, Black\n]            36
[\nFull leather, Beige\n]      36
[\nCloth, Brown\n]             28
[\nVelour\n]                   16
[\nOther, Grey\n]              15
[\nCloth, Beige\n]             13
[\nBrown\n]                    12
[\nCloth, Blue\n]              12
[\nVelour, Grey\n]              8
[\nCloth, White\n]              8
[\nalcantara, Grey\n]           6
[\nCloth, Red\n]                5
[\nOther, Yellow\n]             4
[\nPart leather, Red\n]         3
[\nBeige\n]                     3
[\nPart leather, White\n]       2
[\nFull leather, Blue\n]        2
[\nalcantara, Other\n]          2
[\nalcantara\n]                 2
[\nWhite\n]                     2
[\nPart leather, Beige\n]       2
[\nBlue\n]                      2
[\nCloth, Orange\n]             1
[\nFull leather, Red\n]         1
[\nOther, Brown\n]              1
[\nFull leather, White\n]       1
Name: upholstery, dtype: int64
******************************


In [60]:
# bazı sütunlarda sütun isimleri açıklanır halde birimi ile birlikte yazılacak
# url sonra bakılacak.
# make_model, make ve model sütunları incelenecek eksik veriler tamamlanacak ve make_model veya make ve model sütunu kalacak.
# short_description sonra bakılacak
# body_type da bulunan none değerler doldurulacak. Dolduramazsak other lara ekleyebiliriz
# price sütunu floata çevrilecek (€ simgesi konacak)
# vat(value add tax) sütununda null değerler fazla (28%) bu sütuna bakılacak ve ilişkili olduğunu düşündüğümüz kolonlar vastasıyla doldurulacak
# km sütununda ',' ve 'km' ler arındırılacak. Ayrıca '-' değerlerine bakılıp ne anlama geldiğine bakılacak
# registration ve first registration aynı değerlendirilebilir ve buradan age sütunu oluşturulabilir
# prew_owner çok fazla null değer var. araç yaşına göre düzenlenebilir 
# kw silinecek (Tamamı none değerler)
# hp sütununda 'kw' ler silinecek (hp ye çevrilebilir). strange  değerler var. '-' değerleri var
# type sütunu listeden çıkarağız.fuel ile koordineli doldurma işlemi yapılacak. Yakıt ksıımları silinecek. (pre-registration gibi değerler var  değeri new oalrak değiştirilecek)
# previous_owners '\n' lerden temizlenecek. sütun ile ilgisi olmayan şeyler var
# next_inspection temizlenecek. null değer çok fazla.
# inspection_new çok fazla null değer. diğer sütunları tamamlamaya çalışacağız
# warranty çok fazla null ve boş değer var month ın öündeki sayıları extract yapacağız. inr veya floata çevireceğiz
# full servis sütumu tekrar incelenecek ve önem derecesine bakılıp düşülecek
# non_smoking_vehicle düşülecek
# null sütunu düşülecek
# offer_number bi anlamı yok düşülecek
# body_color a göre grıuplama yapılacak fiyat analizi yapılacak sonra kategorize edilecek
# paint_type sütunu temizlenecek cex kalacak (3 type var metalik non-metalik, perl)
# body_color ve body _color_original birlikte incelenip null değerler doldurrulmaya çalışılacak sonra original silinecek
# upholstery sütunu temizlenecek kategorize edilecek
# body sütunu temizlenecek
# nr_of_doors sütunun da strange value var 
# nr_of_seats temizlenecek null değerler doldurulacak
# model_code tekrar bakılacak ve düşülecek
# gearing_type temizlenecek 
# displacement temizlenecek 'cc' ve ',' değerleri silinecek. ismi 'engine_displacement' değişecek 
# cylinders temizlenecek null değerler doldurmaya çalışılacak. engine displacement sütunu ile birlikte değerlendirilecek
# weight null değerler var temizlenecek düşülebilir veya doldurulabilir veya kategorize edilebilir. 
# drive_chain temizlenecek ve doldurulacak
# fuel kategorize edilecek allen hocanın kodu ile
# consumption temizlenip kategorize edilecek
# co2_emission temizlenip integer a evrilecek
# emission_class değerleri hepsi aynı gibi silinebilir fiyata etkisine bakılacak
# comfort&convenience puanlama mantığı yapılabilir
# entertainment&media puanlama mantığı yapılabilir
# safety_&_security puanlama mantığı yapılabilir
# extras puanlama mantığı yapılabilir
# description düşülecek
# emission_label null değer çok fazla düşülebilir 
# gears tmizlenecek extreme değerler var null değer fazla
# country_version vat sütunu ile değerlendirilecek null lar dolacak
# electricity_consumption düşecek 
# last_service_date düşecek
# other_fuel_types düşecek
# availability düşecek
# last_timing_belt_service_date düşecek 
# available_from düşecek

In [61]:
import re 

def get_diff_category_column(Series:pd.Series, exclude=''',/\n''', pattern=r'''[,\n]| /''', strip='''\n' "!?|.,*+-_/][\\n''', diff_value=list()):  
    diff_value.clear()
    column = Series.dropna().apply(str).str.strip(strip)
    for row in column:
        if not any(x in exclude for x in row) and row not in diff_value:
            diff_value.append(row)
        else:
            for data in map(lambda x: x.strip(strip), filter(None, re.split(pattern, row))):
                if data not in diff_value:
                    diff_value.append(data)
    return dict(enumerate(sorted(diff_value)))

# **1. url**

In [62]:
check_df(["url"])

column name :  ['url']
--------------------------------
Per_of_Nulls   :  % url    0.0
dtype: float64
Num_of_Nulls   :  url    0
dtype: int64
url
https://www.autoscout24.com//offers/audi-a1-1-0-30-tfsi-sportback-advanced-2019-sh-pdc-gasoline-white-1037d13f-0851-44dd-b559-c6f6def8e6d2                     1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-s-s-innovation-at-matrix-led-gasoline-black-8b880006-0c08-4500-91c0-2b45013716c8                   1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-innovation-matrix-navi-pdc-gasoline-silver-bf9ce61b-6d07-4e1a-b734-e5c1742f03b8                    1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-innovation-navi-klimaaut-gasoline-blue-900ec5a8-b2db-427d-8977-8363b8ae15b9                        1
https://www.autoscout24.com//offers/opel-insignia-1-5-turbo-innovation-navi-klimaaut-gasoline-grey-913b914f-a839-416d-96ba-c995de9f4db3                        1
                                                                                                                                                              ..
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-1-5-150-ps-euro-6-wltp-gasoline-white-d84d9ed1-c735-48a1-89ba-d614f7da6a0a                       1
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-110kw-gasoline-00a371f2-061f-4339-87cd-f5605edae75b                                              1
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-150-gps-radars-16p-gasoline-black-2f028979-a6f3-4716-9c76-6e981fb0a3c9                           1
https://www.autoscout24.com//offers/audi-a3-sportback-35-tfsi-150-gps-radars-16p-gasoline-grey-a6344f21-90da-4140-b505-9bd31ec5013e                            1
https://www.autoscout24.com//offers/renault-espace-zu-spaet-geht-an-haendler-da-wird-er-dann-23-000-ko-gasoline-silver-93caa088-19e3-905e-e053-e250040a8d8d    1
Length: 15919, dtype: int64
******************************

In [63]:
# url sütunu analizimize etki etmeyeceği için düşülecek

# **2. make_model, make and model columns**

In [64]:
for i in ["make_model", "make", "model"]:
    check_df(i)

column name :  make_model
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64
******************************



column name :  make
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
\nOpel\n       7343
\nAudi\n       5712
\nRenault\n    2864
Name: make, dtype: int64
******************************



column name :  model
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
[\n, A3, \n]          3097
[\n, A1, \n]          2614
[\n, Insignia, \n]    2598
[\n, Astra, \n]       2526
[\n, Corsa, \n]       2219
[\n, Clio, \n]        1839
[\n, Espace, \n]       991
[\n, Duster, \n]        34
[\n, A2, \n]             1
Name: model, dtype: int64
******************************

In [65]:
df[["make_model", "make", "model"]].sample(50)

          make_model         make               model
12799  Opel Insignia     \nOpel\n  [\n, Insignia, \n]
7615      Opel Astra     \nOpel\n     [\n, Astra, \n]
4063         Audi A3     \nAudi\n        [\n, A3, \n]
5931      Opel Astra     \nOpel\n     [\n, Astra, \n]
10999  Opel Insignia     \nOpel\n  [\n, Insignia, \n]
5437         Audi A3     \nAudi\n        [\n, A3, \n]
7670      Opel Astra     \nOpel\n     [\n, Astra, \n]
6906      Opel Astra     \nOpel\n     [\n, Astra, \n]
13276   Renault Clio  \nRenault\n      [\n, Clio, \n]
13992   Renault Clio  \nRenault\n      [\n, Clio, \n]
6461      Opel Astra     \nOpel\n     [\n, Astra, \n]
12785  Opel Insignia     \nOpel\n  [\n, Insignia, \n]
1557         Audi A1     \nAudi\n        [\n, A1, \n]
13797   Renault Clio  \nRenault\n      [\n, Clio, \n]
7479      Opel Astra     \nOpel\n     [\n, Astra, \n]
527          Audi A1     \nAudi\n        [\n, A1, \n]
10542  Opel Insignia     \nOpel\n  [\n, Insignia, \n]
13905   Renault Clio  \nRenault\n      [\n, Clio, \n]
77           Audi A1     \nAudi\n        [\n, A1, \n]
8246      Opel Corsa     \nOpel\n     [\n, Corsa, \n]
411          Audi A1     \nAudi\n        [\n, A1, \n]
3915         Audi A3     \nAudi\n        [\n, A3, \n]
9367      Opel Corsa     \nOpel\n     [\n, Corsa, \n]
4928         Audi A3     \nAudi\n        [\n, A3, \n]
159          Audi A1     \nAudi\n        [\n, A1, \n]
6006      Opel Astra     \nOpel\n     [\n, Astra, \n]
12447  Opel Insignia     \nOpel\n  [\n, Insignia, \n]
2854         Audi A3     \nAudi\n        [\n, A3, \n]
276          Audi A1     \nAudi\n        [\n, A1, \n]
7181      Opel Astra     \nOpel\n     [\n, Astra, \n]
9740      Opel Corsa     \nOpel\n     [\n, Corsa, \n]
5136         Audi A3     \nAudi\n        [\n, A3, \n]
9783      Opel Corsa     \nOpel\n     [\n, Corsa, \n]
1222         Audi A1     \nAudi\n        [\n, A1, \n]
6121      Opel Astra     \nOpel\n     [\n, Astra, \n]
12828  Opel Insignia     \nOpel\n  [\n, Insignia, \n]
13369   Renault Clio  \nRenault\n      [\n, Clio, \n]
1126         Audi A1     \nAudi\n        [\n, A1, \n]
8920      Opel Corsa     \nOpel\n     [\n, Corsa, \n]
9467      Opel Corsa     \nOpel\n     [\n, Corsa, \n]
969          Audi A1     \nAudi\n        [\n, A1, \n]
4247         Audi A3     \nAudi\n        [\n, A3, \n]
1486         Audi A1     \nAudi\n        [\n, A1, \n]
13849   Renault Clio  \nRenault\n      [\n, Clio, \n]
9896      Opel Corsa     \nOpel\n     [\n, Corsa, \n]
5583         Audi A3     \nAudi\n        [\n, A3, \n]
10713  Opel Insignia     \nOpel\n  [\n, Insignia, \n]
4031         Audi A3     \nAudi\n        [\n, A3, \n]
14585   Renault Clio  \nRenault\n      [\n, Clio, \n]
1661         Audi A1     \nAudi\n        [\n, A1, \n]

In [66]:
df[["make", "model"]] = df.make_model.str.split(" ", expand=True)

In [67]:
# we can drop the make_model column 
df.drop(columns="make_model", inplace=True)

In [68]:
df.head(1).T

                                                                               0
url                            https://www.autoscout24.com//offers/audi-a1-sp...
short_description                    Sportback 1.4 TDI S-tronic Xenon Navi Klima
body_type                                                                 Sedans
price                                                                      15770
vat                                                               VAT deductible
km                                                                     56,013 km
registration                                                             01/2016
prev_owner                                                     2 previous owners
kW                                                                           NaN
hp                                                                         66 kW
type                                     [, Used, , Diesel (Particulate Filter)]
previous_owners                                                            \n2\n
next_inspection                            [\n06/2021\n, \n99 g CO2/km (comb)\n]
inspection_new                                             [\nYes\n, \nEuro 6\n]
warranty                                                 [\n, \n, \n4 (Green)\n]
full_service                                                            [\n, \n]
non_smoking_vehicle                                                     [\n, \n]
null                                                                          []
make                                                                        Audi
model                                                                         A1
offer_number                                                     [\nLR-062483\n]
first_registration                                                [\n, 2016, \n]
body_color                                                       [\n, Black, \n]
paint_type                                                        [\nMetallic\n]
body_color_original                                          [\nMythosschwarz\n]
upholstery                                                    [\nCloth, Black\n]
body                                                            [\n, Sedans, \n]
nr_of_doors                                                              [\n5\n]
nr_of_seats                                                              [\n5\n]
model_code                                                        [\n0588/BDF\n]
gearing_type                                                 [\n, Automatic, \n]
displacement                                                      [\n1,422 cc\n]
cylinders                                                                [\n3\n]
weight                                                            [\n1,220 kg\n]
drive_chain                                                          [\nfront\n]
fuel                                       [\n, Diesel (Particulate Filter), \n]
consumption                    [[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...
co2_emission                                            [\n99 g CO2/km (comb)\n]
emission_class                                                      [\nEuro 6\n]
comfort&convenience            [Air conditioning, Armrest, Automatic climate ...
entertainment&media            [Bluetooth, Hands-free equipment, On-board com...
extras                         [Alloy wheels, Catalytic Converter, Voice Cont...
safety_&_security              [ABS, Central door lock, Daytime running light...
description                    [\n, Sicherheit:,  , Deaktivierung für Beifahr...
emission_label                                                               NaN
gears                                                                        NaN
country_version                                                              NaN
electricity_consumption                                                      NaN
last_service_date                                                            NaN
other_fuel_types                                                             NaN
availability                                                                 NaN
last_timing_belt_service_date                                                NaN
available_from                                                               NaN

# **3.short_description**

In [69]:
check_df("short_description")

column name :  short_description
--------------------------------
Per_of_Nulls   :  % 0.29
Num_of_Nulls   :  46
SPB 1.6 TDI 116 CV S tronic Sport                 64
None                                              46
1.4 66kW (90CV) Selective                         40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH             38
SPB 30 TDI S tronic Business                      35
                                                  ..
K Sports Tourer Business **Navi*Voll**             1
1.0 Turbo ecoFLEX Automatic Elective Park Navi     1
1.6 CDTI Business *Navi*Automatik*Spurh.*          1
1.6 136 CV Automatica Navi E 6 Garanzia Full       1
TCe 225 EDC GPF LIM Deluxe Pano,RFK                1
Name: short_description, Length: 10002, dtype: int64
******************************

In [70]:
# it can be used

# **4.body_type**

In [71]:
check_df("body_type")

column name :  body_type
--------------------------------
Per_of_Nulls   :  % 0.38
Num_of_Nulls   :  60
Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
None               60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64
******************************

In [72]:
# Data is clean already we will fill the missing values

# **5.price**

In [73]:
check_df("price")

column name :  price
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
14990    154
15990    151
10990    139
15900    106
17990    102
        ...
17559      1
17560      1
17570      1
17575      1
39875      1
Name: price, Length: 2956, dtype: int64
******************************

In [74]:
df.rename(columns={"price":"price_€"}, inplace=True)

In [75]:
df["price_€"] = df["price_€"].astype(float)

In [76]:
# Data is clean

# **6. vat**

In [77]:
check_df("vat")

column name :  vat
--------------------------------
Per_of_Nulls   :  % 28.35
Num_of_Nulls   :  4513
VAT deductible      10980
None                 4513
Price negotiable      426
Name: vat, dtype: int64
******************************

In [78]:
# Data is clean already we will fill the missing values

# **7. km**

In [79]:
df.km = df.km.str.replace(" km", "").str.replace(",", "")

In [80]:
df[df.km == "- km"].head(5).T

Empty DataFrame
Columns: []
Index: [url, short_description, body_type, price_€, vat, km, registration, prev_owner, kW, hp, type, previous_owners, next_inspection, inspection_new, warranty, full_service, non_smoking_vehicle, null, make, model, offer_number, first_registration, body_color, paint_type, body_color_original, upholstery, body, nr_of_doors, nr_of_seats, model_code, gearing_type, displacement, cylinders, weight, drive_chain, fuel, consumption, co2_emission, emission_class, comfort&convenience, entertainment&media, extras, safety_&_security, description, emission_label, gears, country_version, electricity_consumption, last_service_date, other_fuel_types, availability, last_timing_belt_service_date, available_from]

In [81]:
#def find_number(text):
#    num = re.findall(r'[0-9]+',text)
#    return " ".join(num)

In [ ]:
#df["km_1"] = df['km'].apply(lambda x: find_number(x))
#print("\Extracting numbers from dataframe columns:")
#print(df)

In [ ]:
df.sample(2).T

,3593,1793
url,https://www.autoscout24.com//offers/audi-a3-rs...,https://www.autoscout24.com//offers/audi-a1-sp...
short_description,RS 3 SPB 2.5 TFSI quattro S tronic,SPB 1.6 TDI 116 CV Metal plus
body_type,Sedans,Other
price_€,58500.0,16900.0
vat,None,VAT deductible
km,10000,18950
registration,05/2018,06/2018
prev_owner,None,1 previous owner
kW,NaN,NaN
hp,294 kW,85 kW
type,"[, Used, , Gasoline]","[, Employee's car, , Diesel (Particulate Filter)]"
previous_owners,NaN,\n1\n
next_inspection,NaN,NaN
inspection_new,NaN,NaN
warranty,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]"
full_service,NaN,NaN
non_smoking_vehicle,NaN,NaN
null,[],[]
make,Audi,Audi
model,A3,A1
offer_number,NaN,[\n231953\n]
first_registration,"[\n, 2018, \n]","[\n, 2018, \n]"
body_color,"[\n, White, \n]","[\n, Black, \n]"
paint_type,NaN,[\nMetallic\n]
body_color_original,NaN,[\nNero mito\n]
upholstery,NaN,"[\nCloth, Black\n]"
body,"[\n, Sedans, \n]","[\n, Other, \n]"
nr_of_doors,[\n5\n],[\n5\n]
nr_of_seats,[\n5\n],[\n4\n]
model_code,NaN,NaN
gearing_type,"[\n, Semi-automatic, \n]","[\n, Manual, \n]"
displacement,"[\n2,480 cc\n]","[\n1,598 cc\n]"
cylinders,[\n5\n],[\n4\n]
weight,"[\n1,585 kg\n]",NaN
drive_chain,NaN,[\nfront\n]
fuel,"[\n, Gasoline, \n]","[\n, Diesel (Particulate Filter), \n]"
consumption,"[[8.3 l/100 km (comb)], [11.3 l/100 km (city)]...","[[3.8 l/100 km (comb)], [4.6 l/100 km (city)],..."
co2_emission,[\n189 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n]
emission_class,[\nEuro 6\n],[\nEuro 6\n]
comfort&convenience,"[Air conditioning, Seat ventilation, Split rea...","[Air conditioning, Armrest, Electrical side mi..."
entertainment&media,[Radio],"[Bluetooth, On-board computer, Radio]"
extras,[Alloy wheels],[Alloy wheels]
safety_&_security,"[Adaptive Cruise Control, Alarm system, Centra...","[ABS, Central door lock, Daytime running light..."
description,[\nAUDI rs 3 2.5 Tfsi quattro s tronic anno 05...,[\nBenvenuti nell'Usato di Saottini Auto spa. ...
emission_label,NaN,[\n1 (No sticker)\n]
gears,[\n7\n],[\n5\n]
country_version,NaN,[\nItaly\n]
electricity_consumption,NaN,NaN
last_service_date,NaN,NaN
other_fuel_types,NaN,NaN
availability,NaN,NaN
last_timing_belt_service_date,NaN,NaN
available_from,NaN,NaN

# **8.registration**

In [83]:
#df_ = df.copy()
#df_['job_title'] = df['job_title'].str.replace(r'[^a-z^A-Z]+', '')
#first_look(df_, 'job_title')

In [84]:
#df['km_2'] = df['km'].str.replace(r'[^0-9]+', '')
#df.head(2).T

In [85]:
check_df("registration")

column name :  registration
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64
******************************

In [86]:
df["registration"] = df.registration.str.extract(r"\d+/(\d*)")

In [87]:
df["registration"]

0        2016
1        2017
2        2016
3        2016
4        2016
         ...
15914     NaN
15915    2019
15916    2019
15917    2019
15918    2019
Name: registration, Length: 15919, dtype: object

In [88]:
df["registration"] = df["registration"].astype(float)

In [89]:
pd.options.display.max_colwidth = 200

# IOT see whole row by max column width

In [ ]:
#df[df.warranty == 12.0][["registration", "model", "make","price_€","entertainment&media", "safety_&_security"]].sample(10)

In [ ]:
#age sütunu oluşturulacak.

In [ ]:
# Data is clean.

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_€                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             15919 non-null  object
 6   registration                   14322 non-null  float64
 7   prev_owner                     9091 non-null   object
 8   kW                             0 non-null      float64
 9   hp                             15919 non-null  object
 10  type                           15917 non-null  object
 11  previous_owners                9279 non-null   object
 12  next_inspection                3535 non-null   object
 13  inspection_new                 3932 non-null   object
 14  warranty                       10499 non-null  object
 15  full_service                   8215 non-null   object
 16  non_smoking_vehicle            7177 non-null   object
 17  null                           15919 non-null  object
 18  make                           15919 non-null  object
 19  model                          15919 non-null  object
 20  offer_number                   12744 non-null  object
 21  first_registration             14322 non-null  object
 22  body_color                     15322 non-null  object
 23  paint_type                     10147 non-null  object
 24  body_color_original            12160 non-null  object
 25  upholstery                     12199 non-null  object
 26  body                           15859 non-null  object
 27  nr_of_doors                    15707 non-null  object
 28  nr_of_seats                    14942 non-null  object
 29  model_code                     4978 non-null   object
 30  gearing_type                   15919 non-null  object
 31  displacement                   15423 non-null  object
 32  cylinders                      10239 non-null  object
 33  weight                         8945 non-null   object
 34  drive_chain                    9061 non-null   object
 35  fuel                           15919 non-null  object
 36  consumption                    14013 non-null  object
 37  co2_emission                   14111 non-null  object
 38  emission_class                 12898 non-null  object
 39  comfort&convenience            14999 non-null  object
 40  entertainment&media            14545 non-null  object
 41  extras                         12957 non-null  object
 42  safety_&_security              14937 non-null  object
 43  description                    15919 non-null  object
 44  emission_label                 3985 non-null   object
 45  gears                          11207 non-null  object
 46  country_version                7586 non-null   object
 47  electricity_consumption        137 non-null    object
 48  last_service_date              566 non-null    object
 49  other_fuel_types               880 non-null    object
 50  availability                   635 non-null    object
 51  last_timing_belt_service_date  16 non-null     object
 52  available_from                 272 non-null    object
dtypes: float64(3), object(50)
memory usage: 6.4+ MB

# **9.prev_owner**

In [92]:
check_df("prev_owner")

column name :  prev_owner
--------------------------------
Per_of_Nulls   :  % 42.89
Num_of_Nulls   :  6828
1 previous owner     8294
None                 6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64
******************************

In [93]:
df['prev_owner'] = df['prev_owner'].str.replace(r'[^0-9]+', '')

In [94]:
df['prev_owner']

0           2
1        None
2           1
3           1
4           1
         ...
15914    None
15915       1
15916       1
15917    None
15918       1
Name: prev_owner, Length: 15919, dtype: object

In [95]:
df['prev_owner'] = df['prev_owner'].astype(float)

In [96]:
# Data is clean.

# **10.kW**

In [97]:
check_df("kW")

column name :  kW
--------------------------------
Per_of_Nulls   :  % 100.0
Num_of_Nulls   :  15919
NaN    15919
Name: kW, dtype: int64
******************************

In [98]:
df.drop(columns="kW", inplace=True)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 52 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_€                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             15919 non-null  object
 6   registration                   14322 non-null  float64
 7   prev_owner                     9091 non-null   float64
 8   hp                             15919 non-null  object
 9   type                           15917 non-null  object
 10  previous_owners                9279 non-null   object
 11  next_inspection                3535 non-null   object
 12  inspection_new                 3932 non-null   object
 13  warranty                       10499 non-null  object
 14  full_service                   8215 non-null   object
 15  non_smoking_vehicle            7177 non-null   object
 16  null                           15919 non-null  object
 17  make                           15919 non-null  object
 18  model                          15919 non-null  object
 19  offer_number                   12744 non-null  object
 20  first_registration             14322 non-null  object
 21  body_color                     15322 non-null  object
 22  paint_type                     10147 non-null  object
 23  body_color_original            12160 non-null  object
 24  upholstery                     12199 non-null  object
 25  body                           15859 non-null  object
 26  nr_of_doors                    15707 non-null  object
 27  nr_of_seats                    14942 non-null  object
 28  model_code                     4978 non-null   object
 29  gearing_type                   15919 non-null  object
 30  displacement                   15423 non-null  object
 31  cylinders                      10239 non-null  object
 32  weight                         8945 non-null   object
 33  drive_chain                    9061 non-null   object
 34  fuel                           15919 non-null  object
 35  consumption                    14013 non-null  object
 36  co2_emission                   14111 non-null  object
 37  emission_class                 12898 non-null  object
 38  comfort&convenience            14999 non-null  object
 39  entertainment&media            14545 non-null  object
 40  extras                         12957 non-null  object
 41  safety_&_security              14937 non-null  object
 42  description                    15919 non-null  object
 43  emission_label                 3985 non-null   object
 44  gears                          11207 non-null  object
 45  country_version                7586 non-null   object
 46  electricity_consumption        137 non-null    object
 47  last_service_date              566 non-null    object
 48  other_fuel_types               880 non-null    object
 49  availability                   635 non-null    object
 50  last_timing_belt_service_date  16 non-null     object
 51  available_from                 272 non-null    object
dtypes: float64(3), object(49)
memory usage: 6.3+ MB

# **11.hp**

In [100]:
check_df("hp")

column name :  hp
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ...
84 kW        1
195 kW       1
44 kW        1
239 kW       1
9 kW         1
Name: hp, Length: 81, dtype: int64
******************************

In [101]:
df["hp"] = df['hp'].str.extract(r"(\d+)").astype(float)

In [102]:
df.rename(columns={"hp" : "hp_kW"}, inplace=True)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 52 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   short_description              15873 non-null  object
 2   body_type                      15859 non-null  object
 3   price_€                        15919 non-null  float64
 4   vat                            11406 non-null  object
 5   km                             15919 non-null  object
 6   registration                   14322 non-null  float64
 7   prev_owner                     9091 non-null   float64
 8   hp_kW                          15831 non-null  float64
 9   type                           15917 non-null  object
 10  previous_owners                9279 non-null   object
 11  next_inspection                3535 non-null   object
 12  inspection_new                 3932 non-null   object
 13  warranty                       10499 non-null  object
 14  full_service                   8215 non-null   object
 15  non_smoking_vehicle            7177 non-null   object
 16  null                           15919 non-null  object
 17  make                           15919 non-null  object
 18  model                          15919 non-null  object
 19  offer_number                   12744 non-null  object
 20  first_registration             14322 non-null  object
 21  body_color                     15322 non-null  object
 22  paint_type                     10147 non-null  object
 23  body_color_original            12160 non-null  object
 24  upholstery                     12199 non-null  object
 25  body                           15859 non-null  object
 26  nr_of_doors                    15707 non-null  object
 27  nr_of_seats                    14942 non-null  object
 28  model_code                     4978 non-null   object
 29  gearing_type                   15919 non-null  object
 30  displacement                   15423 non-null  object
 31  cylinders                      10239 non-null  object
 32  weight                         8945 non-null   object
 33  drive_chain                    9061 non-null   object
 34  fuel                           15919 non-null  object
 35  consumption                    14013 non-null  object
 36  co2_emission                   14111 non-null  object
 37  emission_class                 12898 non-null  object
 38  comfort&convenience            14999 non-null  object
 39  entertainment&media            14545 non-null  object
 40  extras                         12957 non-null  object
 41  safety_&_security              14937 non-null  object
 42  description                    15919 non-null  object
 43  emission_label                 3985 non-null   object
 44  gears                          11207 non-null  object
 45  country_version                7586 non-null   object
 46  electricity_consumption        137 non-null    object
 47  last_service_date              566 non-null    object
 48  other_fuel_types               880 non-null    object
 49  availability                   635 non-null    object
 50  last_timing_belt_service_date  16 non-null     object
 51  available_from                 272 non-null    object
dtypes: float64(4), object(48)
memory usage: 6.3+ MB

In [104]:
#df.drop(columns="km_2", inplace=True)

# **12.type**

In [105]:
check_df("type")

column name :  type
--------------------------------
Per_of_Nulls   :  % 0.01
Num_of_Nulls   :  2
[, Used, , Diesel (Particulate Filter)]                                                                                 3475
[, Used, , Diesel]                                                                                                      2516
[, Used, , Gasoline]                                                                                                    2367
[, Used, , Super 95]                                                                                                    1818
[, Pre-registered, , Super 95]                                                                                           500
                                                                                                                        ...
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]       1
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                               1
[, Demonstration, , Super Plus 98]                                                                                         1
[, New, , Super Plus E10 98]                                                                                               1
[, Demonstration, , Regular/Benzine E10 91]                                                                                1
Name: type, Length: 170, dtype: int64
******************************

In [106]:
 # Changing some columns value type from list to str
df = df.applymap(lambda x: ','.join(map(str,x)) if type(x) == list else x)
df.head()

,url,short_description,body_type,price_€,vat,km,registration,prev_owner,hp_kW,type,previous_owners,next_inspection,inspection_new,warranty,full_service,non_smoking_vehicle,null,make,model,offer_number,first_registration,body_color,paint_type,body_color_original,upholstery,body,nr_of_doors,nr_of_seats,model_code,gearing_type,displacement,cylinders,weight,drive_chain,fuel,consumption,co2_emission,emission_class,comfort&convenience,entertainment&media,extras,safety_&_security,description,emission_label,gears,country_version,electricity_consumption,last_service_date,other_fuel_types,availability,last_timing_belt_service_date,available_from
0,https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770.0,VAT deductible,56013,2016.0,2.0,66.0,",Used,,Diesel (Particulate Filter)",\n2\n,"\n06/2021\n,\n99 g CO2/km (comb)\n","\nYes\n,\nEuro 6\n","\n,\n,\n4 (Green)\n","\n,\n","\n,\n",,Audi,A1,\nLR-062483\n,"\n,2016,\n","\n,Black,\n",\nMetallic\n,\nMythosschwarz\n,"\nCloth, Black\n","\n,Sedans,\n",\n5\n,\n5\n,\n0588/BDF\n,"\n,Automatic,\n","\n1,422 cc\n",\n3\n,"\n1,220 kg\n",\nfront\n,"\n,Diesel (Particulate Filter),\n","['3.8 l/100 km (comb)'],['4.3 l/100 km (city)'],['3.5 l/100 km (country)']",\n99 g CO2/km (comb)\n,\nEuro 6\n,"Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Navigation system,Park Dista...","Bluetooth,Hands-free equipment,On-board computer,Radio","Alloy wheels,Catalytic Converter,Voice Control","ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring...","\n,Sicherheit:, ,Deaktivierung für Beifahrer-Airbag, ,ESC mit elektronischer Quersperre, ,Tagfahrlicht, ,Reifendruck-Kontrollanzeige, ,Kopfairbag-System mit Seiten-Airbags vorn, ,Sicherheitslenksä...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df,1.8 TFSI sport,Sedans,14500.0,Price negotiable,80000,2017.0,NaN,141.0,",Used,,Gasoline",NaN,NaN,NaN,NaN,NaN,NaN,,Audi,A1,NaN,"\n,2017,\n","\n,Red,\n",NaN,NaN,"\nCloth, Grey\n","\n,Sedans,\n",\n3\n,\n4\n,\n0588/BCY\n,"\n,Automatic,\n","\n1,798 cc\n",\n4\n,"\n1,255 kg\n",\nfront\n,"\n,Gasoline,\n","['5.6 l/100 km (comb)'],['7.1 l/100 km (city)'],['4.7 l/100 km (country)']",\n129 g CO2/km (comb)\n,\nEuro 6\n,"Air conditioning,Automatic climate control,Hill Holder,Leather steering wheel,Lumbar support,Parking assist system sensors rear,Power windows,Start-stop system,Tinted windows","Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system","Alloy wheels,Sport seats,Sport suspension,Voice Control","ABS,Central door lock,Central door lock with remote control,Daytime running lights,Driver-side airbag,Electronic stability control,Head airbag,Immobilizer,Isofix,Passenger-side airbag,Power steeri...","\nLangstreckenfahrzeug daher die hohe Kilometerleistung. ,Bremsen neu bei 62000 km. ,Gut gepflegter A1\n",\n4 (Green)\n,\n7\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sportback-1-6-tdi-s-tronic-einparkhilfe-plus-music-diesel-black-6183cb6a-8570-4b86-a132-9b54214bca88,Sportback 1.6 TDI S tronic Einparkhilfe plus+music,Sedans,14640.0,VAT deductible,83450,2016.0,1.0,85.0,",Used,,Diesel (Particulate Filter)",\n1\n,NaN,NaN,"\n,\n,\n99 g CO2/km (comb)\n",NaN,NaN,,Audi,A1,\nAM-95365\n,"\n,2016,\n","\n,Black,\n",\nMetallic\n,\nmythosschwarz metallic\n,"\nCloth, Black\n","\n,Sedans,\n",\n4\n,\n4\n,NaN,"\n,Automatic,\n","\n1,598 cc\n",NaN,NaN,\nfront\n,"\n,Diesel (Particulate Filter),\n","['3.8 l/100 km (comb)'],['4.4 l/100 km (city)'],['3.4 l/100 km (country)']",\n99 g CO2/km (comb)\n,\nEuro 6\n,"Air conditioning,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front...","MP3,On-board computer","Alloy wheels,Voice Control","ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Tra...","\n,Fahrzeug-Nummer: AM-95365, ,Ehem. UPE 24.640 EUR, ,Komfort, ,Klimaanlage, ,Elektrische Fensterheber, ,Sitzheizung, ,Tempomat, ,Zentralverriegelung, ,Leder-Lenkrad, ,Elektrische Spiegel, ,Wärmed...",\n4 (Green)\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-4-tdi-design-s-tronic-diesel-brown-35c86585-2727-d61e-e053-e250040ad640,1.4 TDi Design S tronic,Sedans,14500.0,None,73000,2016.0,1.0,66.0,",Used,,Diesel (Particulate Filter)",\n1\n,NaN,NaN,NaN,"\n,\n,\n99 g CO2/km (comb)\n","\n,\n,\nEuro 6\n",,Audi,A1,NaN,"\n,2016,\n","\n,Brown,\n",\nMetallic\n,NaN,NaN,"\n,Sedans,\n",\n3\n,\n4\n,NaN,"\n,Automatic,\n","\n1,422 cc\n",\n3\n,"\n1,195 kg\n",NaN,"\n,Diesel (Particulate Filter),\n","['3.8 l/100 km (comb)'],['4.3 l/100 km (city)'],['3.5 l/100 km (country)']",\n99 g CO2/km (comb)\n,\nEuro 6\n,"Air suspension,Armrest,Auxiliary heating,Electrical side mirrors,Heads-up display,Hill Holder,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Pow...","Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB","Alloy wheels,Sport seats,Voice Control","ABS,Alarm system,Central door lock with remote control,Driver drowsiness detection,Driver-side airbag,Electronic stability control,Emergency system,Head airbag,Immobilizer,Isofix,Passenger-side ai...","\nAudi A1: ,- 1e eigenaar ,- Perfecte staat: schade/ongevalvrij ,- Onderhoudsboekje Audi garage ,- Full option!,- S-line opties,- Automaat, lederen bekleding, navi-pro, Xenon lampen, zetelverwarmi...",NaN,\n6\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-s-line-ext-admired-xe-diesel-black-b86b55d8-9c7c-4a58-b658-b97008a51efc,"Sportback 1.4 TDI S-Tronic S-Line Ext. admired, Xe",Sedans,16790.0,None,16200,2016.0,1.0,66.0,",Used,,Diesel (Particulate Filter)",\n1\n,NaN,"\nYes\n,\n109 g CO2/km (comb)\n","\n,\n,\nEuro 6\n","\n,\n,\n4 (Green)\n","\n,\n",,Audi,A1,\nC1626\n,"\n,2016,\n","\n,Black,\n",\nMetallic\n,\nMythosschwarz Metallic\n,"\nCloth, Black\n","\n,Sedans,\n",\n5\n,\n5\n,\n0588/BDF\n,"\n,Automatic,\n","\n1,422 cc\n",\n3\n,NaN,\nfront\n,"\n,Diesel (Particulate Filter),\n","['4.1 l/100 km (comb)'],['4.6 l/100 km (city)'],['3.8 l/100 km (country)']",\n109 g CO2/km (comb)\n,\nEuro 6\n,"Air conditioning,Armrest,Automatic climate control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Park Distance Control,Parking assist system...","Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB","Alloy wheels,Sport package,Sport suspension,Voice Control","ABS,Central door lock,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction contro...","\n,Technik & Sicherheit:,Xenon plus,Klimaautomatik,Einparkhilfe hinten,Scheinwerferreinigungsanlage,Nebelscheinwerfer,Zentralverriegelung mit Fernbedienung,Außenspiegel elek. einstellbar,Fensterhe...",NaN,NaN,\nGermany\n,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
df.type = df.type.str.extract(r",(\w+|\w+\W\w+|\w+\W\w\s\w+),")

In [108]:
df.type.value_counts()

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: type, dtype: int64

# **13.previous_owners**

In [109]:
check_df("previous_owners")

column name :  previous_owners
--------------------------------
Per_of_Nulls   :  % 41.71
Num_of_Nulls   :  6640
\n1\n                                                                               8103
NaN                                                                                 6640
\n2\n                                                                                766
\n0\n                                                                                163
\n3\n                                                                                 17
                                                                                    ...
\n1\n,\n111 g CO2/km (comb)\n                                                          1
\n1\n,\nEuro 6\n                                                                       1
\n2\n,\n119 g CO2/km (comb)\n                                                          1
\n1\n,\n,6.6 l/100 km (comb),\n,8.1 l/100 km (city),\n,5.7 l/100 km (country),\n       1
\n1\n,\n142 g CO2/km (comb)\n                                                          1
Name: previous_owners, Length: 102, dtype: int64
******************************

In [110]:
df.previous_owners.sample(60)

11113    \n1\n
4384     \n0\n
1523     \n1\n
8046     \n1\n
6262       NaN
14597      NaN
148      \n1\n
15819      NaN
15171    \n1\n
10578    \n1\n
13563      NaN
13271      NaN
13471      NaN
7624     \n1\n
14029      NaN
4410       NaN
3281       NaN
2924     \n1\n
4642     \n1\n
12652      NaN
3425     \n1\n
6650     \n1\n
5815       NaN
4145       NaN
13673      NaN
6069     \n1\n
2142       NaN
5647       NaN
4564     \n1\n
2080     \n1\n
8137     \n1\n
144      \n2\n
6356     \n1\n
8035       NaN
1144       NaN
8267     \n1\n
2490     \n1\n
9059     \n2\n
15595      NaN
14304    \n1\n
653      \n2\n
4094       NaN
4820     \n1\n
5065       NaN
5318       NaN
3076     \n1\n
15017    \n2\n
11801    \n1\n
8397       NaN
10134    \n1\n
5741     \n1\n
14740    \n0\n
4934     \n1\n
14925      NaN
2437       NaN
3164     \n1\n
4123     \n2\n
4427     \n1\n
1229     \n2\n
4207     \n1\n
Name: previous_owners, dtype: object

In [111]:
df[["prev_owner", "previous_owners"]].sample(5)

       prev_owner previous_owners
6477          2.0           \n2\n
5899          NaN             NaN
277           1.0           \n1\n
2146          NaN             NaN
15852         NaN             NaN

In [112]:
df.previous_owners = df.previous_owners.str.extract(r"(\d+)")

In [113]:
df.previous_owners.value_counts(dropna=False)

1      8294
NaN    6640
2       778
0       188
3        17
4         2
Name: previous_owners, dtype: int64

In [114]:
df.previous_owners = df.previous_owners.astype(float)

#astype(pd.Int64Dtype()) for convert to integer with Null values

In [115]:
#Data is clean
#prev_owners and previous_owners will be controled and we will filled each other and dropped one of them.

# **14.next_inspection**

In [116]:
check_df("next_inspection")

column name :  next_inspection
--------------------------------
Per_of_Nulls   :  % 77.79
Num_of_Nulls   :  12384
NaN                                    12384
\n04/2022\n                               62
\n06/2021\n                               47
\n03/2021\n                               39
\n03/2022\n                               36
                                       ...
\n06/2021\n,\n121 g CO2/km (comb)\n        1
\n02/2020\n,\n139 g CO2/km (comb)\n        1
\n10/2021\n,\n136 g CO2/km (comb)\n        1
\n06/2019\n,\n139 g CO2/km (comb)\n        1
\n01/2022\n,\n168 g CO2/km (comb)\n        1
Name: next_inspection, Length: 1385, dtype: int64
******************************

In [117]:
df.drop(columns="next_inspection", inplace=True)

In [118]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **15.inspection_new**

In [119]:
check_df("inspection_new")

column name :  inspection_new
--------------------------------
Per_of_Nulls   :  % 75.3
Num_of_Nulls   :  11987
NaN                                                                                   11987
\nYes\n,\nEuro 6\n                                                                      523
\nYes\n                                                                                 442
\nYes\n,\n102 g CO2/km (comb)\n                                                         174
\nYes\n,\n4 (Green)\n                                                                   166
                                                                                      ...
\nYes\n,\n,5.2 l/100 km (comb),\n,6.7 l/100 km (city),\n,4.2 l/100 km (country),\n        1
\nYes\n,\n100 g CO2/km (comb)\n                                                           1
\nYes\n,\n,4.9 l/100 km (comb),\n,5.9 l/100 km (city),\n,4.3 l/100 km (country),\n        1
\nYes\n,\n,5.1 l/100 km (comb),\n,6.4 l/100 km (city),\n,4.3 l/100 km (country),\n        1
\nYes\n,\n172 g CO2/km (comb)\n                                                           1
Name: inspection_new, Length: 202, dtype: int64
******************************

In [120]:
df.drop(columns="inspection_new", inplace=True)

In [121]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **16.warranty**

In [122]:
check_df("warranty")

column name :  warranty
--------------------------------
Per_of_Nulls   :  % 34.05
Num_of_Nulls   :  5420
NaN                                                                                       5420
\n,\n,\nEuro 6\n                                                                          1868
\n12 months\n                                                                             1305
\n                                                                                         979
\n24 months\n                                                                              585
                                                                                          ...
\n2 months\n                                                                                 1
\n72 months\n,\n125 g CO2/km (comb)\n                                                        1
\n60 months\n,\n14 g CO2/km (comb)\n                                                         1
\n24 months\n,\n121 g CO2/km (comb)\n                                                        1
\n36 months\n,\n,7.4 l/100 km (comb),\n,9.6 l/100 km (city),\n,6 l/100 km (country),\n       1
Name: warranty, Length: 508, dtype: int64
******************************

In [123]:
df.warranty = df.warranty.str.extract(r"(\d+)\sm+").astype(float)

In [124]:
df.warranty.value_counts().sort_index()

1.0        3
2.0        5
3.0       33
4.0        3
6.0      125
7.0        1
8.0        1
9.0        2
10.0       1
11.0       2
12.0    2594
13.0       3
14.0       2
15.0       1
16.0       4
17.0       2
18.0      10
19.0       3
20.0       7
21.0       2
22.0       2
23.0      11
24.0    1118
25.0       6
26.0       4
28.0       2
30.0       1
33.0       1
34.0       3
36.0     279
40.0       1
45.0       2
46.0       2
47.0       1
48.0     149
49.0       1
50.0       4
56.0       1
60.0     401
65.0       1
72.0      59
Name: warranty, dtype: int64

In [125]:
#data is clean.

# **17.full_service**

In [126]:
check_df("full_service")

column name :  full_service
--------------------------------
Per_of_Nulls   :  % 48.39
Num_of_Nulls   :  7704
NaN                                                                                 7704
\n,\n,\n4 (Green)\n                                                                 2235
\n,\n,\nEuro 6\n                                                                    2097
\n,\n                                                                               1702
\n,\n,\nEuro 6d-TEMP\n                                                               399
                                                                                    ...
\n,\n,\n80 g CO2/km (comb)\n                                                           1
\n,\n,\n84 g CO2/km (comb)\n                                                           1
\n,\n,\n,6 l/100 km (comb),\n,8 l/100 km (city),\n,4.9 l/100 km (country),\n           1
\n,\n,\n,4.9 l/100 km (comb),\n,6.2 l/100 km (city),\n,4.1 l/100 km (country),\n       1
\n,\n,\nEuro 4\n                                                                       1
Name: full_service, Length: 123, dtype: int64
******************************

In [127]:
df.drop(columns="full_service",inplace=True)

In [128]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **18.non_smoking_vehicle**

In [129]:
check_df("non_smoking_vehicle")

column name :  non_smoking_vehicle
--------------------------------
Per_of_Nulls   :  % 54.92
Num_of_Nulls   :  8742
NaN                                                                                 8742
\n,\n                                                                               3647
\n,\n,\n4 (Green)\n                                                                 1240
\n,\n,\nEuro 6\n                                                                    1127
\n,\n,\nEuro 6d-TEMP\n                                                               345
                                                                                    ...
\n,\n,\n,5.6 l/100 km (comb),\n,7.3 l/100 km (city),\n,4.7 l/100 km (country),\n       1
\n,\n,\n122 g CO2/km (comb)\n                                                          1
\n,\n,\n158 g CO2/km (comb)\n                                                          1
\n,\n,\n150 g CO2/km (comb)\n                                                          1
\n,\n,\n175 g CO2/km (comb)\n                                                          1
Name: non_smoking_vehicle, Length: 95, dtype: int64
******************************

In [130]:
df.drop(columns="non_smoking_vehicle",inplace=True)

In [131]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **19.null**

In [132]:
check_df("null")

column name :  null
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
    15919
Name: null, dtype: int64
******************************

In [133]:
df.drop(columns="null",inplace=True)

In [134]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **20.offer_number**

In [135]:
check_df("offer_number")

column name :  offer_number
--------------------------------
Per_of_Nulls   :  % 19.94
Num_of_Nulls   :  3175
NaN                                             3175
\nLT67679\n                                       27
\nUN89904\n                                       27
\nXJ38068\n                                       27
\nJV03654\n                                       27
                                                ...
\n160_dcbb6c3e-a6da-43a3-8754-ccd994cec93b\n       1
\n6701576\n                                        1
\n6701569\n                                        1
\n158121\n                                         1
\nRe_30000008029\n                                 1
Name: offer_number, Length: 11441, dtype: int64
******************************

In [136]:
df.drop(columns="offer_number",inplace=True)

In [137]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **21.first_registration**

In [138]:
check_df("first_registration")

column name :  first_registration
--------------------------------
Per_of_Nulls   :  % 10.03
Num_of_Nulls   :  1597
\n,2018,\n    4522
\n,2016,\n    3674
\n,2017,\n    3273
\n,2019,\n    2853
NaN           1597
Name: first_registration, dtype: int64
******************************

In [139]:
df.drop(columns="first_registration",inplace=True)

In [140]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **22.body_color**

In [141]:
check_df("body_color")

column name :  body_color
--------------------------------
Per_of_Nulls   :  % 3.75
Num_of_Nulls   :  597
\n,Black,\n     3745
\n,Grey,\n      3505
\n,White,\n     3406
\n,Silver,\n    1647
\n,Blue,\n      1431
\n,Red,\n        957
NaN              597
\n,Brown,\n      289
\n,Green,\n      154
\n,Beige,\n      108
\n,Yellow,\n      51
\n,Violet,\n      18
\n,Bronze,\n       6
\n,Orange,\n       3
\n,Gold,\n         2
Name: body_color, dtype: int64
******************************

In [142]:
df.body_color = df.body_color.str.split(",", expand=True)[1]

In [143]:
df.body_color.value_counts()

Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: body_color, dtype: int64

In [144]:
#data is clean

# **23.paint_type**

In [145]:
check_df("paint_type")

column name :  paint_type
--------------------------------
Per_of_Nulls   :  % 36.26
Num_of_Nulls   :  5772
\nMetallic\n       9794
NaN                5772
\nUni/basic\n       347
\nPerl effect\n       6
Name: paint_type, dtype: int64
******************************

In [146]:
df.paint_type.str.extract(r"(\w+\W\w+|\w+)").value_counts(dropna=False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
dtype: int64

In [147]:
df.paint_type = df.paint_type.str.extract(r"(\w+\W\w+|\w+)")

In [148]:
#data is clean

# **24.body_color_original**

In [149]:
check_df("body_color_original")

column name :  body_color_original
--------------------------------
Per_of_Nulls   :  % 23.61
Num_of_Nulls   :  3759
NaN                                  3759
\nOnyx Schwarz\n                      338
\nBianco\n                            282
\nMythosschwarz Metallic\n            238
\nBrillantschwarz\n                   216
                                     ...
\nRouge-Braun (G0Y)\n                   1
\nVARI COLRI DISPONIBILI\n              1
\nKokosnussbraun Metallic\n             1
\nFarbe frei wählbar\n                  1
\nPerlmutt-Weiß Metallic (Weiß)\n       1
Name: body_color_original, Length: 1928, dtype: int64
******************************

In [150]:
df.body_color_original.str.split("\n", expand=True)[1].value_counts(dropna=False)

NaN                              3759
Onyx Schwarz                      338
Bianco                            282
Mythosschwarz Metallic            238
Brillantschwarz                   216
                                 ...
Rouge-Braun (G0Y)                   1
VARI COLRI DISPONIBILI              1
Kokosnussbraun Metallic             1
Farbe frei wählbar                  1
Perlmutt-Weiß Metallic (Weiß)       1
Name: 1, Length: 1928, dtype: int64

In [151]:
df.body_color_original = df.body_color_original.str.split("\n", expand=True)[1]

In [152]:
#data is clean

# **25.upholstery**

In [153]:
check_df("upholstery")

column name :  upholstery
--------------------------------
Per_of_Nulls   :  % 23.37
Num_of_Nulls   :  3720
\nCloth, Black\n           5821
NaN                        3720
\nPart leather, Black\n    1121
\nCloth\n                  1005
\nCloth, Grey\n             891
\nCloth, Other\n            639
\nFull leather, Black\n     575
\nBlack\n                   491
\nGrey\n                    273
\nOther, Other\n            182
\nPart leather\n            140
\nFull leather\n            139
\nFull leather, Brown\n     116
\nPart leather, Grey\n      116
\nOther, Black\n            110
\nFull leather, Other\n      72
\nFull leather, Grey\n       67
\nPart leather, Other\n      65
\nOther\n                    56
\nPart leather, Brown\n      50
\nalcantara, Black\n         47
\nVelour, Black\n            36
\nFull leather, Beige\n      36
\nCloth, Brown\n             28
\nVelour\n                   16
\nOther, Grey\n              15
\nCloth, Beige\n             13
\nBrown\n                    12
\nCloth, Blue\n              12
\nVelour, Grey\n              8
\nCloth, White\n              8
\nalcantara, Grey\n           6
\nCloth, Red\n                5
\nOther, Yellow\n             4
\nPart leather, Red\n         3
\nBeige\n                     3
\nPart leather, White\n       2
\nFull leather, Blue\n        2
\nalcantara, Other\n          2
\nalcantara\n                 2
\nWhite\n                     2
\nPart leather, Beige\n       2
\nBlue\n                      2
\nCloth, Orange\n             1
\nFull leather, Red\n         1
\nOther, Brown\n              1
\nFull leather, White\n       1
Name: upholstery, dtype: int64
******************************

In [154]:
df.upholstery.str.split("\n", expand=True)[1].str.split(",", expand=True)[0].value_counts(dropna=False)

Cloth           8423
NaN             3720
Part leather    1499
Full leather    1009
Black            491
Other            368
Grey             273
Velour            60
alcantara         57
Brown             12
Beige              3
Blue               2
White              2
Name: 0, dtype: int64

In [155]:
#df.upholstery.str.split("\n", expand=True)[1].str.extract(r"(\w+\s?\w+)").value_counts(dropna=False)

In [156]:
df.upholstery = df.upholstery.str.split("\n", expand=True)[1].str.extract(r"(\w+\s?\w+)")

In [158]:
# we assumed that if there is only color info in column, it's cloth's color
Cloths = ['Cloth','Black', 'Grey', 'Blue', 'White', 'Beige', 'Brown']

In [159]:
def upholsterytype(x):
    if x in Cloths:
        return "Cloth"
    elif x == "Full leather":
        return "Full leather"
    elif x == "Part leather":
        return "Part leather"
    elif x == "alcantara":
        return "alcantara"
    elif x== "Velour":
        return "Velour"
    elif x== "Other":
        return "Other"

In [160]:
df["upholstery"] = df["upholstery"].apply(upholsterytype)

In [162]:
df.upholstery.value_counts()

Cloth           9206
Part leather    1499
Full leather    1009
Other            368
Velour            60
alcantara         57
Name: upholstery, dtype: int64

In [ ]:
# Data is clean

# **26.body**

In [163]:
check_df("body")

column name :  body
--------------------------------
Per_of_Nulls   :  % 0.38
Num_of_Nulls   :  60
\n,Sedans,\n           7903
\n,Station wagon,\n    3553
\n,Compact,\n          3153
\n,Van,\n               783
\n,Other,\n             290
\n,Transporter,\n        88
NaN                      60
\n,Off-Road,\n           56
\n,Coupe,\n              25
\n,Convertible,\n         8
Name: body, dtype: int64
******************************

In [165]:
df.body.str.strip("\n,").value_counts()

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body, dtype: int64

In [166]:
df.body_type.value_counts()

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [167]:
df.drop(columns="body", inplace=True)

In [ ]:
#Data is Clean, df.body and df.body_type gave the same result 
#Therefore we dropped body column

# **27.nr_of_doors**

In [168]:
check_df("nr_of_doors")

column name :  nr_of_doors
--------------------------------
Per_of_Nulls   :  % 1.33
Num_of_Nulls   :  212
\n5\n    11575
\n4\n     3079
\n3\n      832
\n2\n      219
NaN        212
\n1\n        1
\n7\n        1
Name: nr_of_doors, dtype: int64
******************************

In [172]:
df.nr_of_doors = df.nr_of_doors.str.strip("\n").astype(float)

In [174]:
df.nr_of_doors.value_counts()

5.0    11575
4.0     3079
3.0      832
2.0      219
1.0        1
7.0        1
Name: nr_of_doors, dtype: int64

In [ ]:
#Data is clean

# **28.nr_of_seats**

In [175]:
check_df("nr_of_seats")

column name :  nr_of_seats
--------------------------------
Per_of_Nulls   :  % 6.14
Num_of_Nulls   :  977
\n5\n    13336
\n4\n     1125
NaN        977
\n7\n      362
\n2\n      116
\n6\n        2
\n3\n        1
Name: nr_of_seats, dtype: int64
******************************

In [178]:
df.nr_of_seats = df.nr_of_seats.str.strip("\n").astype(float)

In [179]:
df.nr_of_seats.value_counts()

5.0    13336
4.0     1125
7.0      362
2.0      116
6.0        2
3.0        1
Name: nr_of_seats, dtype: int64

In [ ]:
#Data is clean

# **29.model_code**

In [180]:
check_df("model_code")

column name :  model_code
--------------------------------
Per_of_Nulls   :  % 68.73
Num_of_Nulls   :  10941
NaN             10941
\n0035/BCB\n      268
\n0588/BNO\n      245
\n0588/BDB\n      206
\n0588/BHX\n      188
                ...
\n0035/AVN\n        1
\n0035/BEM\n        1
\n0035/BAG\n        1
\n0035/BAA\n        1
\n3333/BKG\n        1
Name: model_code, Length: 233, dtype: int64
******************************

In [181]:
df.drop(columns="model_code", inplace=True)

In [ ]:
# It is not relevant to analysis bcs of that we can drop this column without cleaning

# **30.gearing_type**

In [182]:
check_df("gearing_type")

column name :  gearing_type
--------------------------------
Per_of_Nulls   :  % 0.0
Num_of_Nulls   :  0
\n,Manual,\n            8153
\n,Automatic,\n         7297
\n,Semi-automatic,\n     469
Name: gearing_type, dtype: int64
******************************

In [188]:
df.gearing_type = df.gearing_type.str.strip("\n,")

In [189]:
df.gearing_type.value_counts()

Manual            8153
Automatic         7297
Semi-automatic     469
Name: gearing_type, dtype: int64

In [ ]:
#Data is clean

# **31.displacement**

In [190]:
check_df("displacement")

column name :  displacement
--------------------------------
Per_of_Nulls   :  % 3.12
Num_of_Nulls   :  496
\n1,598 cc\n    4761
\n999 cc\n      2438
\n1,398 cc\n    1314
\n1,399 cc\n     749
\n1,229 cc\n     677
                ...
\n122 cc\n         1
\n1,198 cc\n       1
\n1,195 cc\n       1
\n2,967 cc\n       1
\n1,800 cc\n       1
Name: displacement, Length: 78, dtype: int64
******************************

In [191]:
df.displacement.str.strip("\n cc")

0        1,422
1        1,798
2        1,598
3        1,422
4        1,422
         ...
15914    1,997
15915    1,798
15916    1,997
15917    1,997
15918    1,798
Name: displacement, Length: 15919, dtype: object

In [194]:
df.displacement = df.displacement.str.strip("\n cc").str.replace(",", "").astype(float)

In [198]:
df.displacement.value_counts().sort_index(ascending=True)

1.0        36
2.0         2
54.0        1
122.0       1
139.0       4
           ..
2000.0     46
2480.0     20
2967.0      1
15898.0     1
16000.0     1
Name: displacement, Length: 77, dtype: int64

In [199]:
df.rename(columns={"displacement" : "engine_displacement_cc"}, inplace=True)

In [ ]:
#Data is clean.

# **32.cylinders**

In [200]:
check_df("cylinders")

column name :  cylinders
--------------------------------
Per_of_Nulls   :  % 35.68
Num_of_Nulls   :  5680
\n4\n    8105
NaN      5680
\n3\n    2104
\n5\n      22
\n6\n       3
\n8\n       2
\n2\n       2
\n1\n       1
Name: cylinders, dtype: int64
******************************

In [204]:
df.cylinders = df.cylinders.str.strip("\n").astype(float)

In [205]:
df.cylinders.value_counts()

4.0    8105
3.0    2104
5.0      22
6.0       3
8.0       2
2.0       2
1.0       1
Name: cylinders, dtype: int64

In [ ]:
#Data is clean.

# **33.weight**

In [206]:
check_df("weight")

column name :  weight
--------------------------------
Per_of_Nulls   :  % 43.81
Num_of_Nulls   :  6974
NaN             6974
\n1,163 kg\n     574
\n1,360 kg\n     356
\n1,165 kg\n     301
\n1,335 kg\n     242
                ...
\n1,960 kg\n       1
\n1,258 kg\n       1
\n1,167 kg\n       1
\n1,331 kg\n       1
\n2,037 kg\n       1
Name: weight, Length: 435, dtype: int64
******************************

# PART- 2 `( Handling With Missing Vales )`

In [ ]:
get_diff_category_column(df.warranty)

{0: '',
 1: '0 g CO2/km (comb)',
 2: '0 kWh/100 km (comb)',
 3: '087 g CO2/km (comb)',
 4: '1 (No sticker)',
 5: '1 months',
 6: '10 months',
 7: '100 g CO2/km (comb)',
 8: '101 g CO2/km (comb)',
 9: '102 g CO2/km (comb)',
 10: '103 g CO2/km (comb)',
 11: '104 g CO2/km (comb)',
 12: '105 g CO2/km (comb)',
 13: '106 g CO2/km (comb)',
 14: '107 g CO2/km (comb)',
 15: '108 g CO2/km (comb)',
 16: '109 g CO2/km (comb)',
 17: '11 months',
 18: '110 g CO2/km (comb)',
 19: '111 g CO2/km (comb)',
 20: '112 g CO2/km (comb)',
 21: '113 g CO2/km (comb)',
 22: '114 g CO2/km (comb)',
 23: '115 g CO2/km (comb)',
 24: '116 g CO2/km (comb)',
 25: '117 g CO2/km (comb)',
 26: '118 g CO2/km (comb)',
 27: '119 g CO2/km (comb)',
 28: '12',
 29: '12 months',
 30: '120 g CO2/km (comb)',
 31: '121 g CO2/km (comb)',
 32: '122 g CO2/km (comb)',
 33: '123 g CO2/km (comb)',
 34: '124 g CO2/km (comb)',
 35: '125 g CO2/km (comb)',
 36: '126 g CO2/km (comb)',
 37: '127 g CO2/km (comb)',
 38: '128 g CO2/km (comb)',
 39: '129 g CO2/km (comb)',
 40: '13 months',
 41: '130 g CO2/km (comb)',
 42: '131 g CO2/km (comb)',
 43: '132 g CO2/km (comb)',
 44: '133 g CO2/km (comb)',
 45: '134 g CO2/km (comb)',
 46: '135 g CO2/km (comb)',
 47: '136 g CO2/km (comb)',
 48: '137 g CO2/km (comb)',
 49: '138 g CO2/km (comb)',
 50: '139 g CO2/km (comb)',
 51: '14',
 52: '14 g CO2/km (comb)',
 53: '14 months',
 54: '140 g CO2/km (comb)',
 55: '141 g CO2/km (comb)',
 56: '142 g CO2/km (comb)',
 57: '143 g CO2/km (comb)',
 58: '144 g CO2/km (comb)',
 59: '145 g CO2/km (comb)',
 60: '146 g CO2/km (comb)',
 61: '147 g CO2/km (comb)',
 62: '148 g CO2/km (comb)',
 63: '149 g CO2/km (comb)',
 64: '15 months',
 65: '150 g CO2/km (comb)',
 66: '151 g CO2/km (comb)',
 67: '152 g CO2/km (comb)',
 68: '153 g CO2/km (comb)',
 69: '154 g CO2/km (comb)',
 70: '155 g CO2/km (comb)',
 71: '156 g CO2/km (comb)',
 72: '157 g CO2/km (comb)',
 73: '158 g CO2/km (comb)',
 74: '16 months',
 75: '161 g CO2/km (comb)',
 76: '164 g CO2/km (comb)',
 77: '166 g CO2/km (comb)',
 78: '168 g CO2/km (comb)',
 79: '169 g CO2/km (comb)',
 80: '17 months',
 81: '170 g CO2/km (comb)',
 82: '171 g CO2/km (comb)',
 83: '172 g CO2/km (comb)',
 84: '174 g CO2/km (comb)',
 85: '175 g CO2/km (comb)',
 86: '18 months',
 87: '187 g CO2/km (comb)',
 88: '188 g CO2/km (comb)',
 89: '189 g CO2/km (comb)',
 90: '19 months',
 91: '197 g CO2/km (comb)',
 92: '199 g CO2/km (comb)',
 93: '2 months',
 94: '20 months',
 95: '21 months',
 96: '22 months',
 97: '23 months',
 98: '24 months',
 99: '25 months',
 100: '26 months',
 101: '28 months',
 102: '3 months',
 103: '3.8 l/100 km (country)',
 104: '3.9 l/100 km (country)',
 105: '30 months',
 106: '324 g CO2/km (comb)',
 107: '33 months',
 108: '34 months',
 109: '36 months',
 110: '4 (Green)',
 111: '4 l/100 km (country)',
 112: '4 months',
 113: '4.1 l/100 km (country)',
 114: '4.2 l/100 km (country)',
 115: '4.3 l/100 km (comb)',
 116: '4.3 l/100 km (country)',
 117: '4.4 l/100 km (comb)',
 118: '4.4 l/100 km (country)',
 119: '4.5 l/100 km (comb)',
 120: '4.5 l/100 km (country)',
 121: '4.6 l/100 km (country)',
 122: '4.7 l/100 km (comb)',
 123: '4.7 l/100 km (country)',
 124: '4.8 l/100 km (country)',
 125: '4.9 l/100 km (comb)',
 126: '4.9 l/100 km (country)',
 127: '40 months',
 128: '45 g CO2/km (comb)',
 129: '45 months',
 130: '457 g CO2/km (comb)',
 131: '46 months',
 132: '47 months',
 133: '48 months',
 134: '49 months',
 135: '5 (Blue)',
 136: '5 l/100 km (comb)',
 137: '5 l/100 km (country)',
 138: '5.1 l/100 km (city)',
 139: '5.1 l/100 km (comb)',
 140: '5.2 l/100 km (city)',
 141: '5.2 l/100 km (comb)',
 142: '5.2 l/100 km (country)',
 143: '5.3 l/100 km (country)',
 144: '5.4 l/100 km (city)',
 145: '5.4 l/100 km (comb)',
 146: '5.4 l/100 km (country)',
 147: '5.5 l/100 km (city)',
 148: '5.5 l/100 km (comb)',
 149: '5.6 l/100 km (comb)',
 150: '5.6 l/100 km (country)',
 151: '5.7 l/100 km (city)',
 152: '5.7 l/100 km (comb)',
 153: '5.7 l/100 km (country)',
 154: '5.8 l/100 km (comb)',
 155: '5.9 l/100 km (city)',
 156: '5.9 l/100 km (comb)',
 157: '50 months',
 158: '51 g CO2/km (comb)',
 159: '56 months',
 160: '6 l/100 km (city)',
 161: '6 l/100 km (comb)',
 162: '6 l/100 km (country)',
 163: '6 months',
 164: '6.1 l/100 km (comb)',
 165: '6.2 l/100 km (city)',
 166: '6.2 l/100 km (comb)',
 167: '6.3 l/100 km (city)',
 168: '6.3 l/100 km (comb)',
 169: '6.4 l/100 km (comb)',
 170: '6.5 l/100 km (comb)',
 171: '6.6 l/100 km (city)',
 172: '6.6 l/100 km (comb)',
 173: '6.7 l/100 km (city)',
 174: '6.7 l/100 km (comb)',
 175: '6.8 l/100 km (city)',
 176: '6.9 l/100 km (city)',
 177: '60 months',
 178: '65 months',
 179: '7 l/100 km (city)',
 180: '7 months',
 181: '7.1 l/100 km (city)',
 182: '7.2 l/100 km (city)',
 183: '7.3 l/100 km (city)',
 184: '7.4 l/100 km (comb)',
 185: '7.5 l/100 km (city)',
 186: '7.6 l/100 km (city)',
 187: '7.7 l/100 km (city)',
 188: '7.8 l/100 km (city)',
 189: '7.9 l/100 km (city)',
 190: '72 months',
 191: '8 months',
 192: '8.1 l/100 km (city)',
 193: '8.2 l/100 km (city)',
 194: '8.3 l/100 km (city)',
 195: '8.5 l/100 km (city)',
 196: '8.6 l/100 km (city)',
 197: '82 g CO2/km (comb)',
 198: '85 g CO2/km (comb)',
 199: '87 g CO2/km (comb)',
 200: '88 g CO2/km (comb)',
 201: '89 g CO2/km (comb)',
 202: '9 months',
 203: '9.6 l/100 km (city)',
 204: '90 g CO2/km (comb)',
 205: '91 g CO2/km (comb)',
 206: '92 g CO2/km (comb)',
 207: '93 g CO2/km (comb)',
 208: '94 g CO2/km (comb)',
 209: '95 g CO2/km (comb)',
 210: '96 g CO2/km (comb)',
 211: '97 g CO2/km (comb)',
 212: '98 g CO2/km (comb)',
 213: '99 g CO2/km (comb)',
 214: 'Diesel',
 215: 'Euro 4',
 216: 'Euro 5',
 217: 'Euro 6',
 218: 'Euro 6c',
 219: 'Euro 6d',
 220: 'Euro 6d-TEMP'}

# PART- 3 `( Handling With Outliers )`

# Final Step (Checking final situation of data via graphs)

## Export dataframe to csv file (without dummy)

In [ ]:
df.to_csv("final_scout_not_dummy.csv", index=False)

# Dummy Operation

## Export dataframe to csv file (dummy)

In [ ]:
df_dummied.to_csv("final_scout_dummy.csv", index=False)